### ISSUE TITLE
[BUG] Build time dependency Cython not declared

### ISSUE THREAD

**Issue by astrojuanlu** [alan-turing-institute/sktime#1150]
**Describe the bug**

The `setup.py` file uses `setup_requires` to declare `wheel` as a build-time dependency. However, it looks like Cython is also needed, because I got this eror on a fresh virtualenv with Python 3.7 on Linux Mint:

```
(.venv) juanlu@arion2:~/Projects/RTD/sktime$ pip install .
Processing /home/juanlu/Projects/RTD/sktime
Requirement already satisfied: numpy>=1.19.0 in ./.venv/lib/python3.7/site-packages (from sktime==0.7.0) (1.21.0)
Requirement already satisfied: pandas>=1.1.0 in ./.venv/lib/python3.7/site-packages (from sktime==0.7.0) (1.3.0)
Requirement already satisfied: scikit-learn>=0.24.0 in ./.venv/lib/python3.7/site-packages (from sktime==0.7.0) (0.24.2)
Requirement already satisfied: statsmodels>=0.12.1 in ./.venv/lib/python3.7/site-packages (from sktime==0.7.0) (0.12.2)
Requirement already satisfied: numba>=0.50 in ./.venv/lib/python3.7/site-packages (from sktime==0.7.0) (0.53.1)
Requirement already satisfied: wheel in ./.venv/lib/python3.7/site-packages (from sktime==0.7.0) (0.36.2)
Requirement already satisfied: pytz>=2017.3 in ./.venv/lib/python3.7/site-packages (from pandas>=1.1.0->sktime==0.7.0) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in ./.venv/lib/python3.7/site-packages (from pandas>=1.1.0->sktime==0.7.0) (2.8.2)
Requirement already satisfied: joblib>=0.11 in ./.venv/lib/python3.7/site-packages (from scikit-learn>=0.24.0->sktime==0.7.0) (1.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./.venv/lib/python3.7/site-packages (from scikit-learn>=0.24.0->sktime==0.7.0) (2.2.0)
Requirement already satisfied: scipy>=0.19.1 in ./.venv/lib/python3.7/site-packages (from scikit-learn>=0.24.0->sktime==0.7.0) (1.7.0)
Requirement already satisfied: patsy>=0.5 in ./.venv/lib/python3.7/site-packages (from statsmodels>=0.12.1->sktime==0.7.0) (0.5.1)
Requirement already satisfied: llvmlite<0.37,>=0.36.0rc1 in ./.venv/lib/python3.7/site-packages (from numba>=0.50->sktime==0.7.0) (0.36.0)
Requirement already satisfied: setuptools in ./.venv/lib/python3.7/site-packages (from numba>=0.50->sktime==0.7.0) (47.1.0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas>=1.1.0->sktime==0.7.0) (1.16.0)
Building wheels for collected packages: sktime
  Building wheel for sktime (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/juanlu/Projects/RTD/sktime/.venv/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-7f5ynf47/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-7f5ynf47/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-setbtybz
       cwd: /tmp/pip-req-build-7f5ynf47/
  Complete output (27 lines):
  C compiler: x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fdebug-prefix-map=/build/python3.7-7jazGd/python3.7-3.7.11=. -fstack-protector-strong -Wformat -Werror=format-security -g -fdebug-prefix-map=/build/python3.7-7jazGd/python3.7-3.7.11=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC

  compile options: '-c'
  extra options: '-fopenmp'
  x86_64-linux-gnu-gcc: test_openmp.c
  x86_64-linux-gnu-gcc -pthread objects/test_openmp.o -o test_openmp -fopenmp
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-7f5ynf47/setup.py", line 325, in <module>
      setup_package()
    File "/tmp/pip-req-build-7f5ynf47/setup.py", line 321, in setup_package
      setup(**metadata)
    File "/home/juanlu/Projects/RTD/sktime/.venv/lib/python3.7/site-packages/numpy/distutils/core.py", line 135, in setup
      config = configuration()
    File "/tmp/pip-req-build-7f5ynf47/setup.py", line 216, in configuration
      config.add_subpackage("sktime")
    File "/home/juanlu/Projects/RTD/sktime/.venv/lib/python3.7/site-packages/numpy/distutils/misc_util.py", line 1018, in add_subpackage
      caller_level = 2)
    File "/home/juanlu/Projects/RTD/sktime/.venv/lib/python3.7/site-packages/numpy/distutils/misc_util.py", line 987, in get_subpackage
      caller_level = caller_level + 1)
    File "/home/juanlu/Projects/RTD/sktime/.venv/lib/python3.7/site-packages/numpy/distutils/misc_util.py", line 924, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "sktime/setup.py", line 28, in configuration
      maybe_cythonize_extensions(top_path, config)
    File "/tmp/pip-req-build-7f5ynf47/sktime/_build_utils/__init__.py", line 53, in maybe_cythonize_extensions
      import Cython
  ModuleNotFoundError: No module named 'Cython'
  ----------------------------------------
  ERROR: Failed building wheel for sktime
  Running setup.py clean for sktime
Failed to build sktime
Installing collected packages: sktime
    Running setup.py install for sktime ... error
    ERROR: Command errored out with exit status 1:
     command: /home/juanlu/Projects/RTD/sktime/.venv/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-7f5ynf47/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-7f5ynf47/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-43rk2weh/install-record.txt --single-version-externally-managed --compile --install-headers /home/juanlu/Projects/RTD/sktime/.venv/include/site/python3.7/sktime
         cwd: /tmp/pip-req-build-7f5ynf47/
    Complete output (27 lines):
    C compiler: x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fdebug-prefix-map=/build/python3.7-7jazGd/python3.7-3.7.11=. -fstack-protector-strong -Wformat -Werror=format-security -g -fdebug-prefix-map=/build/python3.7-7jazGd/python3.7-3.7.11=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC

    compile options: '-c'
    extra options: '-fopenmp'
    x86_64-linux-gnu-gcc: test_openmp.c
    x86_64-linux-gnu-gcc -pthread objects/test_openmp.o -o test_openmp -fopenmp
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-7f5ynf47/setup.py", line 325, in <module>
        setup_package()
      File "/tmp/pip-req-build-7f5ynf47/setup.py", line 321, in setup_package
        setup(**metadata)
      File "/home/juanlu/Projects/RTD/sktime/.venv/lib/python3.7/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/tmp/pip-req-build-7f5ynf47/setup.py", line 216, in configuration
        config.add_subpackage("sktime")
      File "/home/juanlu/Projects/RTD/sktime/.venv/lib/python3.7/site-packages/numpy/distutils/misc_util.py", line 1018, in add_subpackage
        caller_level = 2)
      File "/home/juanlu/Projects/RTD/sktime/.venv/lib/python3.7/site-packages/numpy/distutils/misc_util.py", line 987, in get_subpackage
        caller_level = caller_level + 1)
      File "/home/juanlu/Projects/RTD/sktime/.venv/lib/python3.7/site-packages/numpy/distutils/misc_util.py", line 924, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "sktime/setup.py", line 28, in configuration
        maybe_cythonize_extensions(top_path, config)
      File "/tmp/pip-req-build-7f5ynf47/sktime/_build_utils/__init__.py", line 53, in maybe_cythonize_extensions
        import Cython
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/juanlu/Projects/RTD/sktime/.venv/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-7f5ynf47/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-7f5ynf47/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-43rk2weh/install-record.txt --single-version-externally-managed --compile --install-headers /home/juanlu/Projects/RTD/sktime/.venv/include/site/python3.7/sktime Check the logs for full command output.
WARNING: You are using pip version 20.1.1; however, version 21.1.3 is available.
You should consider upgrading via the '/home/juanlu/Projects/RTD/sktime/.venv/bin/python3.7 -m pip install --upgrade pip' command.
```

**Expected behavior**
`pip` installs all required build-time dependencies.

**Additional context**
Instead of `setup_requires`, would the project be open to switching to PEP-518 `pyproject.toml` build-time dependencies instead? It would look something like this:

```diff
diff --git a/pyproject.toml b/pyproject.toml
new file mode 100644
index 00000000..2bf5ec80
--- /dev/null
+++ b/pyproject.toml
@@ -0,0 +1,3 @@
+[build-system]
+requires = ["setuptools", "wheel", "Cython"]
+build-backend = "setuptools.build_meta"
diff --git a/setup.py b/setup.py
index 89ddbc96..5f35b06b 100644
--- a/setup.py
+++ b/setup.py
@@ -101,8 +101,6 @@ CLASSIFIERS = [
     "Programming Language :: Python :: 3.8",
 ]
 
-SETUP_REQUIRES = ["wheel"]
-
 # Optional setuptools features
 # For some commands, use setuptools
 SETUPTOOLS_COMMANDS = {
@@ -278,7 +276,6 @@ def setup_package():
         classifiers=CLASSIFIERS,
         cmdclass=cmdclass,
         python_requires=">={}".format(MIN_PYTHON_VERSION),
-        setup_requires=SETUP_REQUIRES,
         install_requires=INSTALL_REQUIRES,
         extras_require=EXTRAS_REQUIRE,
         **extra_setuptools_args

```

However, it didn't work because there is some extra logic in `setup.py`:

https://github.com/alan-turing-institute/sktime/blob/9ca7587bedc861b039a3d9a822ed7ad03ba935ad/setup.py#L314-L315

as well as `sktime/setup.py` (which fails while doing `from sktime._build_utils import maybe_cythonize_extensions`).

**Comment by fkiraly** [comment]
resolved - `cython` is no longer a dependency since 0.10.0
