### ISSUE TITLE
[BUG] sporadic bug in clustering example notebook

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1228]
When running the clustering notebook in PR #1209 completely unrelated to clustering, the test_examples check resulted in the following failure:

```
[NbConvertApp] Converting notebook examples/partition_based_clustering.ipynb to notebook
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.11/x64/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/jupyter_core/application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 346, in start
    self.convert_notebooks()
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 518, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 483, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 412, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 143, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 318, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 84, in preprocess
    self.preprocess_cell(cell, resources, index)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 105, in preprocess_cell
    cell = self.execute_cell(cell, index, store_history=True)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
k_medoids = TimeSeriesKMedoids(
    n_clusters=5,  # Number of desired centers
    init_algorithm="forgy",  # Center initialisation technique
    max_iter=200,  # Maximum number of iterations for refinement on training set
    verbose=False,  # Verbose
    metric="dtw",  # Distance metric to use
)

k_medoids.fit(X_train)
plot_cluster_algorithm(k_medoids, X_test, k_medoids.n_clusters)
------------------

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_3017/3264997074.py in <module>
      7 )
      8 
----> 9 k_medoids.fit(X_train)
     10 plot_cluster_algorithm(k_medoids, X_test, k_medoids.n_clusters)

/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/sktime/clustering/_k_medoids.py in fit(self, X, y)
     87         """
     88 
---> 89         return super(TimeSeriesKMedoids, self).fit(X)
     90 
     91     def predict(self, X: NumpyOrDF) -> NumpyArray:

/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/sktime/clustering/base/base.py in fit(self, X, y)
     53 
     54         self._check_params(X)
---> 55         self._fit(X)
     56 
     57         self._is_fitted = True

/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/sktime/clustering/partitioning/_lloyds_partitioning.py in _fit(self, X, y)
    130 
    131         for _ in range(self.max_iter):
--> 132             self._update_centers(X)
    133 
    134     def _predict(self, X: NumpyArray) -> NumpyArray:

/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/sktime/clustering/partitioning/_lloyds_partitioning.py in _update_centers(self, data)
    217         new_centers = []
    218         for cluster_series in cluster_values:
--> 219             new_centers_i = self.calculate_new_centers(cluster_series)
    220             new_centers.append(new_centers_i)
    221 

/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/sktime/clustering/_k_medoids.py in calculate_new_centers(self, cluster_values)
    127 
    128         medoid = Medoids(cluster_values, self._metric)
--> 129         medoid_index = medoid.approximate()
    130         return cluster_values[medoid_index]

/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/sktime/clustering/partitioning/_cluster_approximations.py in approximate(self)
     36             Index position of the approximation in the series
     37         """
---> 38         distance_matrix = compute_pairwise_distances(X=self.series, metric=self.metric)
     39         return np.argmin(sum(distance_matrix))

/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/sktime/clustering/base/clustering_utils.py in compute_pairwise_distances(metric, X, Y, pairwise_func)
     56         Y = X
     57 
---> 58     return pairwise_func(X=X, Y=Y, metric=dist_wrapper)
     59 
     60 

/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/sklearn/utils/validation.py in inner_f(*args, **kwargs)
     61             extra_args = len(args) - len(all_args)
     62             if extra_args <= 0:
---> 63                 return f(*args, **kwargs)
     64 
     65             # extra_args > 0

/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/sklearn/metrics/pairwise.py in pairwise_distances(X, Y, metric, n_jobs, force_all_finite, **kwds)
   1788         func = partial(distance.cdist, metric=metric, **kwds)
   1789 
-> 1790     return _parallel_pairwise(X, Y, func, n_jobs, **kwds)
   1791 
   1792 

/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/sklearn/metrics/pairwise.py in _parallel_pairwise(X, Y, func, n_jobs, **kwds)
   1357 
   1358     if effective_n_jobs(n_jobs) == 1:
-> 1359         return func(X, Y, **kwds)
   1360 
   1361     # enforce a threading backend to prevent data communication overhead

/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/sklearn/metrics/pairwise.py in _pairwise_callable(X, Y, metric, force_all_finite, **kwds)
   1377     """Handle the callable case for pairwise_{distances,kernels}.
   1378     """
-> 1379     X, Y = check_pairwise_arrays(X, Y, force_all_finite=force_all_finite)
   1380 
   1381     if X is Y:

/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/sklearn/utils/validation.py in inner_f(*args, **kwargs)
     61             extra_args = len(args) - len(all_args)
     62             if extra_args <= 0:
---> 63                 return f(*args, **kwargs)
     64 
     65             # extra_args > 0

/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/sklearn/metrics/pairwise.py in check_pairwise_arrays(X, Y, precomputed, dtype, accept_sparse, force_all_finite, copy)
    142         X = Y = check_array(X, accept_sparse=accept_sparse, dtype=dtype,
    143                             copy=copy, force_all_finite=force_all_finite,
--> 144                             estimator=estimator)
    145     else:
    146         X = check_array(X, accept_sparse=accept_sparse, dtype=dtype,

/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/sklearn/utils/validation.py in inner_f(*args, **kwargs)
     61             extra_args = len(args) - len(all_args)
     62             if extra_args <= 0:
---> 63                 return f(*args, **kwargs)
     64 
     65             # extra_args > 0

/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/sklearn/utils/validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator)
    696                     "Reshape your data either using array.reshape(-1, 1) if "
    697                     "your data has a single feature or array.reshape(1, -1) "
--> 698                     "if it contains a single sample.".format(array))
    699 
    700         # make sure we actually converted to numeric:

ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

Error: Process completed with exit code 1.
```

**Comment by fkiraly** [comment]
@TonyBagnall, @chrisholder, what is this? Your code...

**Comment by fkiraly** [comment]
FYI, no such bug in the rerun, so the bug must be sporadic.

**Comment by chrisholder** [comment]
Sorry literally no idea why I've not seen this until just now - This is my stuff no idea what is going on here. What im working on atm with the distance stuff and pairwise distances will replace this so hopefully this will be fixed when I merge that in so won't have to worry about this.

**Comment by chrisholder** [comment]
Kmedoids has now been completely overhauled with our new distances and bugs like this should no longer exist
