### ISSUE TITLE
[BUG] python/miniconda 3.8 fails CI

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1252]
Since recently, it would appear that the python/miniconda 3.8 builds fail, consistently across PR.
It's always the same traceback:

```
python setup.py build_ext --compiler=msvc
Traceback (most recent call last):
  File "setup.py", line 339, in <module>
    setup_package()
  File "setup.py", line 329, in setup_package
    check_package_status(package, version)
  File "setup.py", line 245, in check_package_status
    module = importlib.import_module(package)
  File "C:\Miniconda38-x64\envs\testenv\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Miniconda38-x64\envs\testenv\lib\site-packages\sklearn\__init__.py", line 82, in <module>
    from .base import clone
  File "C:\Miniconda38-x64\envs\testenv\lib\site-packages\sklearn\base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "C:\Miniconda38-x64\envs\testenv\lib\site-packages\sklearn\utils\__init__.py", line 20, in <module>
    from scipy.sparse import issparse
  File "C:\Miniconda38-x64\envs\testenv\lib\site-packages\scipy\__init__.py", line 136, in <module>
    from . import _distributor_init
  File "C:\Miniconda38-x64\envs\testenv\lib\site-packages\scipy\_distributor_init.py", line 59, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Miniconda38-x64\envs\testenv\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Miniconda38-x64\envs\testenv\lib\site-packages\scipy\.libs\libbanded5x.X7D476RWJKO3TRH4FXIEB4YEAKNOYBT4.gfortran-win_amd64.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

What is this? 3.6 and 3.7 are just fine.

**Comment by fkiraly** [comment]
`gfortran-win_amd64.dll` ???
