### ISSUE TITLE
[BUG] BATS/TBATS multiprocessing crashing when n_jobs!=1

### ISSUE THREAD

**Issue by IlyasMoutawwakil** [alan-turing-institute/sktime#1426]
> **Describe the bug**

The problem started when I put a BATS forecaster in an AutoEnsembleForecaster and ended up with an infinite loop of errors.
But apparently it comes from BATS/TBATS when given n_jobs other than None (default) or 1.

> **To Reproduce**`

```python
import numpy as np
from sktime.datasets import load_airline
from sktime.forecasting.bats import BATS

y = load_airline()
fh = np.arange(1, 10)

bats_forecaster = BATS(sp=[12],
                  use_trend=None,
                  n_jobs=2,
                  use_box_cox=None,
                  use_arma_errors=True,
                  use_damped_trend=None,
                  show_warnings=False)

bats_forecaster.fit(y)
print(bats_forecaster.predict(fh))
```
You should get this long error that keeps on repeating itself infinitely:

```
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "<string>", line 1, in <module>
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
      exitcode = _main(fd, parent_sentinel)
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\multiprocessing\spawn.py", line 125, in _main
      exitcode = _main(fd, parent_sentinel)
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\multiprocessing\spawn.py", line 125, in _main
      prepare(preparation_data)
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\multiprocessing\spawn.py", line 236, in prepare
      prepare(preparation_data)
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\multiprocessing\spawn.py", line 236, in prepare
      _fixup_main_from_path(data['init_main_from_path'])
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
      _fixup_main_from_path(data['init_main_from_path'])
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
      main_content = runpy.run_path(main_path,
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\runpy.py", line 265, in run_path
      main_content = runpy.run_path(main_path,
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\runpy.py", line 265, in run_path
      return _run_module_code(code, init_globals, run_name,
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\runpy.py", line 97, in _run_module_code
      return _run_module_code(code, init_globals, run_name,
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\runpy.py", line 97, in _run_module_code
      _run_code(code, mod_globals, init_globals,
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\runpy.py", line 87, in _run_code
      _run_code(code, mod_globals, init_globals,
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "c:\Users\IlyasMoutawwakil\Documents\test.py", line 23, in <module>
      exec(code, run_globals)
    File "c:\Users\IlyasMoutawwakil\Documents\test.py", line 23, in <module>
      bats_forecaster.fit(y)
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\site-packages\sktime\forecasting\base\_base.py", line 178, in fit
      bats_forecaster.fit(y)
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\site-packages\sktime\forecasting\base\_base.py", line 178, in fit
      self._fit(y=y_inner, X=X_inner, fh=fh)
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\site-packages\sktime\forecasting\base\adapters\_tbats.py", line 91, in _fit
      self._fit(y=y_inner, X=X_inner, fh=fh)
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\site-packages\sktime\forecasting\base\adapters\_tbats.py", line 91, in _fit
      self._forecaster = self._forecaster.fit(y)
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\site-packages\tbats\abstract\Estimator.py", line 98, in fit
      self._forecaster = self._forecaster.fit(y)
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\site-packages\tbats\abstract\Estimator.py", line 98, in fit
      best_model = self._do_fit(y)
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\site-packages\tbats\bats\BATS.py", line 75, in _do_fit
      best_model = self._do_fit(y)
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\site-packages\tbats\bats\BATS.py", line 75, in _do_fit
      return self._choose_model_from_possible_component_settings(y, components_grid)
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\site-packages\tbats\abstract\Estimator.py", line 143, in _choose_model_from_possible_component_settings
      return self._choose_model_from_possible_component_settings(y, components_grid)
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\site-packages\tbats\abstract\Estimator.py", line 143, in _choose_model_from_possible_component_settings
      with self.context.multiprocessing().Pool(processes=self.n_jobs) as pool:
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\multiprocessing\context.py", line 119, in Pool
      with self.context.multiprocessing().Pool(processes=self.n_jobs) as pool:
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\multiprocessing\context.py", line 119, in Pool
      return Pool(processes, initializer, initargs, maxtasksperchild,
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\multiprocessing\pool.py", line 212, in __init__
      return Pool(processes, initializer, initargs, maxtasksperchild,
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\multiprocessing\pool.py", line 212, in __init__
      self._repopulate_pool()
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\multiprocessing\pool.py", line 303, in _repopulate_pool
      self._repopulate_pool()
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\multiprocessing\pool.py", line 303, in _repopulate_pool
      return self._repopulate_pool_static(self._ctx, self.Process,
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
      return self._repopulate_pool_static(self._ctx, self.Process,
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
      w.start()
      w.start()
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\multiprocessing\process.py", line 121, in start
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\multiprocessing\process.py", line 121, in start
      self._popen = self._Popen(self)
      self._popen = self._Popen(self)
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\multiprocessing\context.py", line 327, in _Popen
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\multiprocessing\context.py", line 327, in _Popen
      return Popen(process_obj)
      return Popen(process_obj)
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
      prep_data = spawn.get_preparation_data(process_obj._name)
      prep_data = spawn.get_preparation_data(process_obj._name)
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
      _check_not_importing_main()
      _check_not_importing_main()
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    File "C:\Users\IlyasMoutawwakil\anaconda3\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
      raise RuntimeError('''
      raise RuntimeError('''
  RuntimeError:
          An attempt has been made to start a new process before the
          current process has finished its bootstrapping phase.
  
          This probably means that you are not using fork to start your
          in the main module:
  
              if __name__ == '__main__':
                  freeze_support()
                  ...
  
          The "freeze_support()" line can be omitted if the program
          is not going to be frozen to produce an executable.RuntimeError:
          An attempt has been made to start a new process before the
          current process has finished its bootstrapping phase.
  
          This probably means that you are not using fork to start your
          child processes and you have forgotten to use the proper idiom
          in the main module:
  
              if __name__ == '__main__':
                  freeze_support()
                  ...
  
          The "freeze_support()" line can be omitted if the program
          is not going to be frozen to produce an executable.
```

> **Expected behavior**

Running the forecaster on multiple processes for faster convergence.

> **Additional context**

**Versions**
<details>
System:
    python: 3.8.11 (default, Aug  3 2021, 06:49:12) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\sysnav\anaconda3\python.exe
   machine: Windows-10-10.0.19042-SP0

Python dependencies:
          pip: 21.2.2
   setuptools: 52.0.0.post20210125
      sklearn: 0.24.2
       sktime: 0.7.0
  statsmodels: 0.12.2
        numpy: 1.20.3
        scipy: 1.7.1
       Cython: 0.29.24
       pandas: 1.2.4
   matplotlib: 3.4.2
       joblib: 1.0.1
        numba: 0.54.0
     pmdarima: 1.8.2
      tsfresh: None
</details>

**Comment by mloning** [comment]
I can't reproduce the error on my machine (macOS). Not sure what might be causing it. @IlyasMoutawwakil could you try if the original BATS package works for you?

**Comment by aiwalter** [comment]
I also cant reproduce it. I am on Windows.

**Comment by IlyasMoutawwakil** [comment]
It's coming from [multiprocessing on Windows](https://docs.python.org/2/library/multiprocessing.html#windows) since it doesn't have the `os.fork` . The way around it is to launch training in the context `if __name__ == '__main__':` .
Anyways, thank you guys I'll close this issue.

**Comment by fkiraly** [comment]
might be a good idea to curate a "known issues" list with links to upstream packages?
