### ISSUE TITLE
[BUG] Dev version Installation does not work on Google Colab

### ISSUE THREAD

**Issue by ngupta23** [alan-turing-institute/sktime#2319]
**Describe the bug**
Dev version Installation does not work on Google Colab

**To Reproduce**
```bash
# https://www.sktime.org/en/stable/installation.html#development-versions
!git clone https://github.com/alan-turing-institute/sktime.git
%cd sktime
!git checkout main
!git pull
%ls
!pip install .
```

```bash
Cloning into 'sktime'...
remote: Enumerating objects: 29733, done.
remote: Counting objects: 100% (4502/4502), done.
remote: Compressing objects: 100% (1857/1857), done.
remote: Total 29733 (delta 3176), reused 3734 (delta 2639), pack-reused 25231
Receiving objects: 100% (29733/29733), 45.00 MiB | 12.18 MiB/s, done.
Resolving deltas: 100% (20559/20559), done.
/content/sktime
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
Branch 'forecasting-pipeline-capability-fix' set up to track remote branch 'forecasting-pipeline-capability-fix' from 'origin'.
Switched to a new branch 'forecasting-pipeline-capability-fix'
build_tools/        CONTRIBUTORS.md        GOVERNANCE.md   README.md
CHANGELOG.md        docs/                  LICENSE         setup.cfg
CODE_OF_CONDUCT.md  ESTIMATOR_OVERVIEW.md  Makefile        setup.py
CODEOWNERS          examples/              MANIFEST.in     sktime/
CONTRIBUTING.md     extension_templates/   pyproject.toml
Collecting build
  Downloading build-0.7.0-py3-none-any.whl (16 kB)
Requirement already satisfied: importlib-metadata>=0.22 in /usr/local/lib/python3.7/dist-packages (from build) (4.11.3)
Requirement already satisfied: pep517>=0.9.1 in /usr/local/lib/python3.7/dist-packages (from build) (0.12.0)
Requirement already satisfied: packaging>=19.0 in /usr/local/lib/python3.7/dist-packages (from build) (21.3)
Requirement already satisfied: tomli>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from build) (2.0.1)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=0.22->build) (3.10.0.2)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=0.22->build) (3.7.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=19.0->build) (3.0.7)
Installing collected packages: build
Successfully installed build-0.7.0
* Creating venv isolated environment...

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/build/__main__.py", line 373, in main
    args.srcdir, outdir, distributions, config_settings, not args.no_isolation, args.skip_dependency_check
  File "/usr/local/lib/python3.7/dist-packages/build/__main__.py", line 202, in build_package
    out = _build(isolation, builder, outdir, distribution, config_settings, skip_dependency_check)
  File "/usr/local/lib/python3.7/dist-packages/build/__main__.py", line 140, in _build
    return _build_in_isolated_env(builder, outdir, distribution, config_settings)
  File "/usr/local/lib/python3.7/dist-packages/build/__main__.py", line 104, in _build_in_isolated_env
    with _IsolatedEnvBuilder() as env:
  File "/usr/local/lib/python3.7/dist-packages/build/env.py", line 104, in __enter__
    executable, scripts_dir = _create_isolated_env_venv(self._path)
  File "/usr/local/lib/python3.7/dist-packages/build/env.py", line 257, in _create_isolated_env_venv
    venv.EnvBuilder(with_pip=True, symlinks=_fs_supports_symlink()).create(path)
  File "/usr/lib/python3.7/venv/__init__.py", line 68, in create
    self._setup_pip(context)
  File "/usr/lib/python3.7/venv/__init__.py", line 288, in _setup_pip
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/tmp/build-env-ewrr5k1k/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.

ERROR Command '['/tmp/build-env-ewrr5k1k/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
Processing /content/sktime
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
WARNING: Discarding file:///content/sktime. Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.7/dist-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmprcu0d1h7 Check the logs for full command output.
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.7/dist-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmprcu0d1h7 Check the logs for full command output.
```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by lmmentel** [comment]
Thanks for reporting. I just checked and it seems it's related to the recent change in #2299 where license information was moved around. Here's what I see from the logs

```
Using pip 22.0.4 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)
Processing /content/sktime
  Running command pip subprocess to install build dependencies
  Using pip 22.0.4 from /tmp/pip-standalone-pip-d63y4olc/__env_pip__.zip/pip (python 3.7)
  Collecting setuptools
    Using cached setuptools-61.1.1-py3-none-any.whl (1.1 MB)
  Collecting wheel
    Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
  Collecting toml
    Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
  Collecting build
    Using cached build-0.7.0-py3-none-any.whl (16 kB)
  Collecting tomli>=1.0.0
    Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
  Collecting pep517>=0.9.1
    Using cached pep517-0.12.0-py2.py3-none-any.whl (19 kB)
  Collecting importlib-metadata>=0.22
    Using cached importlib_metadata-4.11.3-py3-none-any.whl (18 kB)
  Collecting packaging>=19.0
    Using cached packaging-21.3-py3-none-any.whl (40 kB)
  Collecting zipp>=0.5
    Using cached zipp-3.7.0-py3-none-any.whl (5.3 kB)
  Collecting typing-extensions>=3.6.4
    Using cached typing_extensions-4.1.1-py3-none-any.whl (26 kB)
  Collecting pyparsing!=3.0.5,>=2.0.2
    Using cached pyparsing-3.0.7-py3-none-any.whl (98 kB)
  Installing collected packages: zipp, wheel, typing-extensions, tomli, toml, setuptools, pyparsing, packaging, importlib-metadata, pep517, build
    Creating /tmp/pip-build-env-fs5iv_y9/overlay/bin
    changing mode of /tmp/pip-build-env-fs5iv_y9/overlay/bin/wheel to 755
    changing mode of /tmp/pip-build-env-fs5iv_y9/overlay/bin/pyproject-build to 755
  ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
  tensorflow 2.8.0 requires tf-estimator-nightly==2.8.0.dev2021122109, which is not installed.
  datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
  arviz 0.11.4 requires typing-extensions<4,>=3.7.4.3, but you have typing-extensions 4.1.1 which is incompatible.
  albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
  Successfully installed build-0.7.0 importlib-metadata-4.11.3 packaging-21.3 pep517-0.12.0 pyparsing-3.0.7 setuptools-61.1.1 toml-0.10.2 tomli-2.0.1 typing-extensions-4.1.1 wheel-0.37.1 zipp-3.7.0
  WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  Getting requirements to build wheel ... done
  Running command Preparing metadata (pyproject.toml)
  running dist_info
  creating /tmp/pip-modern-metadata-2o3j4938/sktime.egg-info
  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "/usr/local/lib/python3.7/dist-packages/setuptools/build_meta.py", line 166, in prepare_metadata_for_build_wheel
      self.run_setup()
    File "/usr/local/lib/python3.7/dist-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 70, in <module>
      setup_package()
    File "setup.py", line 65, in setup_package
      zip_safe=False,
    File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.7/dist-packages/setuptools/_distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.7/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.7/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.7/dist-packages/setuptools/command/dist_info.py", line 31, in run
      egg_info.run()
    File "/usr/local/lib/python3.7/dist-packages/setuptools/command/egg_info.py", line 292, in run
      writer(self, ep.name, os.path.join(self.egg_info, ep.name))
    File "/usr/local/lib/python3.7/dist-packages/setuptools/command/egg_info.py", line 635, in write_pkg_info
      metadata.write_pkg_info(cmd.egg_info)
    File "/usr/local/lib/python3.7/dist-packages/setuptools/_distutils/dist.py", line 1118, in write_pkg_info
      self.write_pkg_file(pkg_info)
    File "/usr/local/lib/python3.7/dist-packages/setuptools/dist.py", line 185, in write_pkg_file
      license = rfc822_escape(self.get_license())
    File "/usr/local/lib/python3.7/dist-packages/setuptools/_distutils/util.py", line 533, in rfc822_escape
      lines = header.split('\n')
  AttributeError: 'dict' object has no attribute 'split'
```

@fkiraly any thoughts?

**Comment by fkiraly** [comment]
I ... have no idea.

Looks like we have the decision to break either all of `sktime` or only `sktime` on colab...

Any good ideas?

**Comment by fkiraly** [comment]
seems to be resolved now, see https://github.com/sktime/sktime/issues/2033
