### ISSUE TITLE
[BUG] sporadic error in `datasets._single_problem_loaders.load_UCR_UEA_dataset`

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#2467]
There seems to be a sporadic (?) error in sporadic error in `datasets._single_problem_loaders.load_UCR_UEA_dataset`, raising an `UNEXPECTED EXCEPTION: ContentTooShortError('retrieval incomplete: got only 4709302 out of 20908976 bytes')`

Run here: https://github.com/alan-turing-institute/sktime/runs/6019508933?check_suite_focus=true

FYI @TonyBagnall, this seems to be yours?

```
____ [doctest] sktime.datasets._single_problem_loaders.load_UCR_UEA_dataset ____
[gw0] linux -- Python 3.7.12 /opt/hostedtoolcache/Python/3.7.12/x64/bin/python
088         series associated with each case. If return_X_y is False, column
089         n_dimensions+1 contains the class labels/target variable.
090     y: numpy array, optional
091         The class labels for each case in X, returned separately if return_X_y is
092         True, or appended to X if False
093 
094     Examples
095     --------
096     >>> from sktime.datasets import load_UCR_UEA_dataset
097     >>> X, y = load_UCR_UEA_dataset(name="Yoga")
UNEXPECTED EXCEPTION: ContentTooShortError('retrieval incomplete: got only 4709302 out of 20908976 bytes')
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/doctest.py", line 1337, in __run
    compileflags, 1), test.globs)
  File "<doctest sktime.datasets._single_problem_loaders.load_UCR_UEA_dataset[1]>", line 1, in <module>
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/sktime/datasets/_single_problem_loaders.py", line 99, in load_UCR_UEA_dataset
    return _load_dataset(name, split, return_X_y, extract_path)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/sktime/datasets/_data_io.py", line 153, in _load_dataset
    extract_path=extract_path,
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/sktime/datasets/_data_io.py", line 79, in _download_and_extract
    urlretrieve(url, zip_file_name)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/urllib/request.py", line 288, in urlretrieve
    % (read, size), result)
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 4709302 out of 20908976 bytes>
/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/sktime/datasets/_single_problem_loaders.py:97: UnexpectedException
```

**Comment by TonyBagnall** [comment]
If it's sporadic it's probably a website issue or problem with your connection, it downloads from tsc.com, which seems to have failed

**Comment by AurumnPegasus** [comment]
Facing the same in #3232 for (3.9, macOS-11) 

```
_________ [doctest] sktime.datasets._single_problem_loaders.load_solar _________
[gw2] darwin -- Python 3.9.13 /Users/runner/hostedtoolcache/Python/3.9.13/x64/bin/python
1048 
1049     References
1050     ----------
1051     .. [1] https://www.solar.sheffield.ac.uk/pvlive/
1052     .. [2] https://www.solar.sheffield.ac.uk/pvlive/api/
1053 
1054     Examples
1055     --------
1056     >>> from sktime.datasets import load_solar
1057     >>> y = load_solar()
UNEXPECTED EXCEPTION: URLError(gaierror(8, 'nodename nor servname provided, or not known'))
```
