### ISSUE TITLE
[BUG] sktime.distances.elastic cannot be found

### ISSUE THREAD

**Issue by drew-hill** [alan-turing-institute/sktime#2652]
**Describe the bug**

Python 3.9.12
sktime==0.11.4

When attempting to utilize the sktime.distances.elastic module, I receive the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'sktime.distances.elastic'
```

Loading sktime.distances by itself produces no errors.

Loading sktime.distances.elastic in a version < 0.11.0 produces no errors as well.

**To Reproduce**

With Python 3.9.12 using the latest sktime v 0.11.4, open python and attempt the following:

'from sktime.distances.elastic import dtw_distance'

```
python -c "from sktime.distances.elastic import dtw_distance"
```

**Expected behavior**

No error or message.

**Additional context**

**Versions**
Python 3.9.12
sktime==0.11.4

... not sure what's going on here. Could this be related to the above error?

```
<path removed by drew-hill>.venv/lib/python3.9/site-packages/_distutils_hack/__init__.py:17: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
  warnings.warn(
<path removed by drew-hill>/.venv/lib/python3.9/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<path removed by drew-hill>/.venv/lib/python3.9/site-packages/sktime/utils/_maint/_show_versions.py", line 85, in show_versions
    deps_info = _get_deps_info()
  File "<path removed by drew-hill>/.venv/lib/python3.9/site-packages/sktime/utils/_maint/_show_versions.py", line 73, in _get_deps_info
    mod = importlib.import_module(modname)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<path removed by drew-hill>/.venv/lib/python3.9/site-packages/setuptools/__init__.py", line 8, in <module>
    import _distutils_hack.override  # noqa: F401
  File "<path removed by drew-hill>/.venv/lib/python3.9/site-packages/_distutils_hack/override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "<path removed by drew-hill>/.venv/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 72, in do_override
    ensure_local_distutils()
  File "<path removed by drew-hill>/.venv/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 59, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
AssertionError: /usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py
```

**Comment by fkiraly** [comment]
I think this is not a bug - the `distances.elastic` module no longer exists, after deprecation.

Distances are now directly imported from the `distances` module, i.e., you need to 

```python
from sktime.distances import dtw_distance
```

**Comment by drew-hill** [comment]
Oh, I totally missed that deprecation. If this works -- which I'll test right now -- perhaps this bug report could be transitioned into a feature request re: a more prominent warning on the "elastic" module's deprecation?

**Comment by fkiraly** [comment]
>Oh, I totally missed that deprecation

Well, I hope it did get deprecated...

>a more prominent warning on the "elastic" module's deprecation?

Typically, we stay compatible and warn for one full minor version cycle, and two for big changes.
The warning would come too late, since the module is no longer there, and code referring to it breaks since 0.11.0.

I just checked the release notes, and it appears no deprecation was noted in 0.10.0?

@TonyBagnall, @chrisholder, do you remember when this has happened? I thought it got removed in 0.10.0, when C got removed?

**Comment by fkiraly** [comment]
The "clean" way to deprecate would be to forward imports of `distances.elastic` to `distances` and raise a `DeprecationWarning` wherever someone imports anything from `distances.elastic`. I just opened up 0.10.0, and that does not seem to have happened. Oh well - too late...

**Comment by drew-hill** [comment]
Importing directly from 'sktime.distances' did the trick. Thanks!

And no sweat -- glad to have it sorted and now folks will at least stumble across the "solution" here if they find themselves in a similar boat. Thanks again for your help!

**Comment by fkiraly** [comment]
I think there´s no action here since the deprecation continuity is already broken, unfortunately. Sorry again, @drew-hill, and glad to read that it works now.
