### ISSUE TITLE
[BUG] Error with n_jobs when MiniRocket is used with calibration

### ISSUE THREAD

**Issue by k-olsen** [alan-turing-institute/sktime#2662]
**Describe the bug**

An error is produced when the `MiniRocket` transform is used with `sklearn`'s `CalibratedClassifierCV` and `n_jobs` is set to any integer _except_ 1 or 2. If `n_jobs=1` or `n_jobs=2` the error is not produced.

If `n_jobs = -1` is used in `MiniRocket` _without_ wrapping the model with `sklearn.calibration.CalibratedClassifierCV` the error does not occur.

**To Reproduce**

```python
from sktime.transformations.panel import rocket
from sktime.datasets import load_arrow_head
import sklearn.pipeline
import sklearn.calibration

X, y = load_arrow_head(return_X_y=True)
n_jobs = -1


featurizer_rocket = rocket.MiniRocket(n_jobs=n_jobs)
classifier = sklearn.ensemble.HistGradientBoostingClassifier(loss='categorical_crossentropy')

base_estimator = sklearn.pipeline.Pipeline(
    [
        ("featurizer_rocket", featurizer_rocket),
        ("classifier", classifier),
    ],
)

calibrated_model = sklearn.calibration.CalibratedClassifierCV(
    base_estimator, cv=2, n_jobs=n_jobs,
)

calibrated_model.fit(X, y)
```
Error:
```
"""
Traceback (most recent call last):
  File "/Users/kira/.pyenv/versions/3.8.10/envs/venv/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 436, in _process_worker
    r = call_item()
  File "/Users/kira/.pyenv/versions/3.8.10/envs/venv/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/Users/kira/.pyenv/versions/3.8.10/envs/venv/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/Users/kira/.pyenv/versions/3.8.10/envs/venv/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/Users/kira/.pyenv/versions/3.8.10/envs/venv/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/Users/kira/.pyenv/versions/3.8.10/envs/venv/lib/python3.8/site-packages/sklearn/utils/fixes.py", line 216, in __call__
    return self.function(*args, **kwargs)
  File "/Users/kira/.pyenv/versions/3.8.10/envs/venv/lib/python3.8/site-packages/sklearn/calibration.py", line 511, in _fit_classifier_calibrator_pair
    estimator.fit(X_train, y_train)
  File "/Users/kira/.pyenv/versions/3.8.10/envs/venv/lib/python3.8/site-packages/sklearn/pipeline.py", line 390, in fit
    Xt = self._fit(X, y, **fit_params_steps)
  File "/Users/kira/.pyenv/versions/3.8.10/envs/venv/lib/python3.8/site-packages/sklearn/pipeline.py", line 348, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "/Users/kira/.pyenv/versions/3.8.10/envs/venv/lib/python3.8/site-packages/joblib/memory.py", line 349, in __call__
    return self.func(*args, **kwargs)
  File "/Users/kira/.pyenv/versions/3.8.10/envs/venv/lib/python3.8/site-packages/sklearn/pipeline.py", line 893, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/Users/kira/.pyenv/versions/3.8.10/envs/venv/lib/python3.8/site-packages/sktime/transformations/base.py", line 434, in fit_transform
    return self.fit(X, y).transform(X, y)
  File "/Users/kira/.pyenv/versions/3.8.10/envs/venv/lib/python3.8/site-packages/sktime/transformations/base.py", line 369, in transform
    Xt = self._transform(X=X_inner, y=y_inner)
  File "/Users/kira/.pyenv/versions/3.8.10/envs/venv/lib/python3.8/site-packages/sktime/transformations/panel/rocket/_minirocket.py", line 122, in _transform
    set_num_threads(n_jobs)
  File "/Users/kira/.pyenv/versions/3.8.10/envs/venv/lib/python3.8/site-packages/numba/np/ufunc/parallel.py", line 587, in set_num_threads
    snt_check(n)
  File "/Users/kira/.pyenv/versions/3.8.10/envs/venv/lib/python3.8/site-packages/numba/np/ufunc/parallel.py", line 549, in snt_check
    raise ValueError(msg)
ValueError: The number of threads must be between 1 and 1
"""

The above exception was the direct cause of the following exception:
ValueError                                Traceback (most recent call last)
     [13] base_estimator = sklearn.pipeline.Pipeline(
     [14]     [
     [15]         ("featurizer_rocket", featurizer_rocket),
     [16]         ("classifier", classifier),
     [17]     ],
     [18] )
     [20] calibrated_model = sklearn.calibration.CalibratedClassifierCV(
     [21]     base_estimator, cv=2, n_jobs=n_jobs,
     [22] )
---> [24] calibrated_model.fit(X, y)

File ~/.pyenv/versions/3.8.10/envs/venv/lib/python3.8/site-packages/sklearn/calibration.py:341, in CalibratedClassifierCV.fit(self, X, y, sample_weight)
    [338] if self.ensemble:
    [339]     parallel = Parallel(n_jobs=self.n_jobs)
--> [341]     self.calibrated_classifiers_ = parallel(
    [342]         delayed(_fit_classifier_calibrator_pair)(
    [343]             clone(base_estimator),
    [344]             X,
    [345]             y,
    [346]            train=train,
    [347]             test=test,
    [348]             method=self.method,
    [349]             classes=self.classes_,
    [350]             supports_sw=supports_sw,
    [351]             sample_weight=sample_weight,
    [352]         )
    [353]         for train, test in cv.split(X, y)
    [354]     )
    [355] else:
    [356]     this_estimator = clone(base_estimator)

File ~/.pyenv/versions/3.8.10/envs/venv/lib/python3.8/site-packages/joblib/parallel.py:1056, in Parallel.__call__(self, iterable)
   [1053]    self._iterating = False
   [1055] with self._backend.retrieval_context():
-> [1056]     self.retrieve()
   [1057] # Make sure that we get a last message telling us we are done
   [1058] elapsed_time = time.time() - self._start_time

File ~/.pyenv/versions/3.8.10/envs/venv/lib/python3.8/site-packages/joblib/parallel.py:935, in Parallel.retrieve(self)
    [933] try:
    [934]     if getattr(self._backend, 'supports_timeout', False):
--> [935]         self._output.extend(job.get(timeout=self.timeout))
    [936]     else:
    [937]         self._output.extend(job.get())

File ~/.pyenv/versions/3.8.10/envs/venv/lib/python3.8/site-packages/joblib/_parallel_backends.py:542, in LokyBackend.wrap_future_result(future, timeout)
    [539] """Wrapper for Future.result to implement the same behaviour as
    [540] AsyncResults.get from multiprocessing."""
    [541] try:
--> [542]     return future.result(timeout=timeout)
    [543] except CfTimeoutError as e:
    [544]     raise TimeoutError from e

File ~/.pyenv/versions/3.8.10/lib/python3.8/concurrent/futures/_base.py:444, in Future.result(self, timeout)
    [442]     raise CancelledError()
    [443] elif self._state == FINISHED:
--> [444]     return self.__get_result()
    [445] else:
    [446]     raise TimeoutError()

File ~/.pyenv/versions/3.8.10/lib/python3.8/concurrent/futures/_base.py:389, in Future.__get_result(self)
    [387] if self._exception:
    [388]     try:
--> [389]         raise self._exception
    [390]     finally:
    [391]        # Break a reference cycle with the exception in self._exception
    [392]         self = None

ValueError: The number of threads must be between 1 and 1
```

**Expected behavior**

Expected `n_jobs = -1` to work without an error.
**Additional context**

**Versions**
<details>

System:
    python: 3.8.10 (default, Jan 10 2022, 10:11:20)  [Clang 13.0.0 (clang-1300.0.29.3)]
executable: /Users/kira/.pyenv/versions/3.8.10/envs/venv/bin/python
   machine: macOS-12.3.1-arm64-arm-64bit

Python dependencies:
          pip: 22.1
   setuptools: 62.2.0
      sklearn: 1.0.2
       sktime: 0.11.4
  statsmodels: 0.13.2
        numpy: 1.21.5
        scipy: 1.7.3
       pandas: 1.4.2
   matplotlib: 3.5.1
       joblib: 1.1.0
        numba: 0.56.0dev0+418.g637a75023
     pmdarima: None
      tsfresh: None
</details>

**Comment by TonyBagnall** [comment]
hi, I just reproduced this error. The problem seems to be that minirocket internally sets the number of threads to be multiprocessing.cpu_count() when n_jobs<1 and this somehow interferes with thecallibration.  If I comment out this block of code changing n_jobs it works fine. I will investigate further and get back to you, 

![image](https://user-images.githubusercontent.com/9594042/196637007-69817e2c-2d05-4695-a436-369578f516be.png)

**Comment by TonyBagnall** [comment]
note the same error occurs in Rocket, MultiRocket, MiniRocketMultivariate and MultiRocketMultivariate (last two on BasicMotions). Tagging @angus924 in this, I don't want to hack around inside rocket without his input :)

**Comment by angus924** [comment]
My only, not-very-useful comment for the moment is that I didn't add the `set_num_threads` etc code.  Hack around freely!  My guess, probably wrong, is that sklearn is trying to use all the threads (via joblib) and, completely separately, numba is trying to use all the threads.

I would assume in this kind of situation, it probably makes sense for sklearn to deal with the multiprocessing and each call to MiniRocket (or whatever) would be on a single thread... rather than sklearn using multiple threads, each thread in turn trying to start multiple new threads, etc.

Sorry, that is probably not helpful at all.

**Comment by TonyBagnall** [comment]
thanks Angus, a licence to hack! Only kidding, I will look further.

**Comment by TonyBagnall** [comment]
so my simple solution to this is to remove the code from _transform that does this
        # change n_jobs dependend on value and existing cores
Firstly, it is introducing behaviour the user may not be aware of (if they want more jobs than cores, good luck to them) and secondly, it is introducing this bug when interacting with scikit learn. CODEOWNERS for rocket based are @ChangWeiTan @fstinner @angus924. Any thoughts on this?

**Comment by TonyBagnall** [comment]
looked a little closer, and I don't think this usage can be made valid, or even if it should. 

Its easier to see whats happening if you set n_jobs above to 4. This then creates a MiniRocket with n_jobs = 4, and a CalibratedClassifierCV with n_jobs = 4 and cross validation set to 2. CalibratedClassifierCV runs each CV train split in Parallel(n_jobs=4). 

This will then clone MiniRocket for each fold, with MiniRocket also set to use n_jobs = 4. Somewhere deep in the threaded code, a check is made to see if the code running in the CV has an allowable number of n_jobs  (like all threaded code its a bit of a mare to degbug).

So, upshot is, if I set n_jobs = 4 for MiniRocket and cv=2, n_jobs = 4 for CalibratedClassifierCV in the above example, I get this

"ValueError: The number of threads must be between 1 and 2"

ah ha, I think, it is assigning 2 jobs to each CV, so if I set n_jobs to 8, I should get between 1 and 4 .... Nope
"ValueError: The number of threads must be between 1 and 1"
which makes no sense. So I cant figure out exactly how CalibratedClassifierCV is assigning jobs between folds, but I am pretty sure the interference is created by the fact that CalibratedClassifierCV is allocating jobs to folds without it successfully changing n_jobs of components in the Pipeline. It is possible there could be an internal mechanism for dynamically changing this, but it is beyond me at the moment. Logically, Im not sure its sensible. If I manually set n_jobs for rocket to 4, and it is then cloned twice, would I expect my main thread to use 8 processes, or to change the rocket setting to 2? I'm not sure. 

So my advice is to set n_jobs for either CalibratedClassifierCV  or for the components, but not both (I checked, both these usages work). I'm not sure how to capture this for a user to see, a MiniRocket does not know its in a pipeline or a CalibratedClassifierCV, nor should it. Really, this should be documented in the scikit documentation I think,

**Comment by angus924** [comment]
This all makes sense.  I agree: one or the other, but not both.  And, I assume, almost certainly parallelism should be used at the "outer most" layer, i.e., `CalibratedClassifierCV` in this case.

I suppose there could be some sort of note in the comments, or perhaps we could try to catch the particular exception (if it's being raised on the `set_num_threads(...)` call)?

**Comment by TonyBagnall** [comment]
threaded code, I have no idea where its being raised other than in Parallel :) Pretty sure it is being raised in the scikit code though, or the Parallel because of the settings in scikit

**Comment by TonyBagnall** [comment]
maybe a note in the docs describing the parameter, n_jobs, "do not set if using with CalibratedClassifierCV " or something?
