### ISSUE TITLE
[BUG] Cannot launch examples on Binder

### ISSUE THREAD

**Issue by ZiyaoWei** [alan-turing-institute/sktime#2775]
**Describe the bug**

Launch binder doesn't work from the links on e.g., https://www.sktime.org/en/latest/examples/01_forecasting.html.

**To Reproduce**

Click on the launch binder button, the launch would get stuck and eventually timeout with the following logs:

```
Waiting for build to start...
Picked Git content provider.
Cloning into '/tmp/repo2dockerxxee58pf'...
HEAD is now at d0f394b7 [ENH] pipeline for time series classification from sktime transformers and sklearn classifiers (#2718)
Using DockerBuildPack builder
Step 1/14 : FROM  jupyter/scipy-notebook:python-3.8.8
 ---> a2c3cd97b4e6
Step 2/14 : ARG NB_USER
 ---> Using cache
 ---> 9c2d9022fb61
Step 3/14 : ARG NB_UID
 ---> Using cache
 ---> c6dfb8ce1a70
Step 4/14 : ENV USER ${NB_USER}
 ---> Using cache
 ---> 570ca0bfdebc
Step 5/14 : ENV HOME /home/${NB_USER}
 ---> Using cache
 ---> b2a537f5a677
Step 6/14 : COPY . ${HOME}
 ---> f18b13557227
Step 7/14 : USER root
 ---> Running in 8dfc8b30747e
Removing intermediate container 8dfc8b30747e
 ---> 77b5a3524eec
Step 8/14 : RUN chown -R ${NB_UID} ${HOME}
 ---> Running in 501665dc09ad
Removing intermediate container 501665dc09ad
 ---> 0c8f8acba4d9
Step 9/14 : USER ${USER}
 ---> Running in 4767d94b04be
Removing intermediate container 4767d94b04be
 ---> 4a1c67eaccb6
Step 10/14 : WORKDIR ${HOME}
 ---> Running in a99fb247ee85
Removing intermediate container a99fb247ee85
 ---> c9060cae0eac
Step 11/14 : RUN pip install --upgrade pip --no-cache-dir && pip install .[binder]
 ---> Running in 91b2634b701f
ERROR: Exception:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/opt/conda/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 204, in wrapper
    return func(self, options, args)
  File "/opt/conda/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 278, in run
    wheel_cache = WheelCache(options.cache_dir, options.format_control)
  File "/opt/conda/lib/python3.8/site-packages/pip/_internal/cache.py", line 238, in __init__
    self._ephem_cache = EphemWheelCache(format_control)
  File "/opt/conda/lib/python3.8/site-packages/pip/_internal/cache.py", line 209, in __init__
    self._temp_dir = TempDirectory(
  File "/opt/conda/lib/python3.8/site-packages/pip/_internal/utils/temp_dir.py", line 130, in __init__
    path = self._create(kind)
  File "/opt/conda/lib/python3.8/site-packages/pip/_internal/utils/temp_dir.py", line 174, in _create
    path = os.path.realpath(tempfile.mkdtemp(prefix=f"pip-{kind}-"))
  File "/opt/conda/lib/python3.8/tempfile.py", line 358, in mkdtemp
    _os.mkdir(file, 0o700)
OSError: [Errno 28] No space left on device: '/tmp/pip-ephem-wheel-cache-w4j1yt23'
Removing intermediate container 91b2634b701f
The command '/bin/bash -o pipefail -c pip install --upgrade pip --no-cache-dir && pip install .[binder]' returned a non-zero code: 2Built image, launching...
Failed to connect to event stream
```

**Expected behavior**

Notebook launches successfully.

**Versions**

Not applicable

**Comment by fkiraly** [comment]
Confirmed, I get the same, connecting from Amsterdam.

It would be useful to hear from people when it worked last, for them.

**Comment by fkiraly** [comment]
Now I'm getting a different error:
```
Error during build: 500 Server Error for http+docker://localhost/v1.41/build?t=gcr.io%2Fbinderhub-288415%2Fr2d-staging-g5b5b759-alan-2dturing-2dinstitute-2dsktime-486400%3A680edaa10f11f089d619be9086fa165fb6a2d151&q=False&nocache=False&rm=True&forcerm=True&pull=False&dockerfile=.binder%2FDockerfile&memory=3221225472&memswap=3221225472&buildargs=%7B%22NB_USER%22%3A+%22jovyan%22%2C+%22NB_UID%22%3A+%221000%22%7D&labels=%7B%22repo2docker.version%22%3A+%222022.02.0%2B32.ge7524a7%22%2C+%22repo2docker.repo%22%3A+%22https%3A%2F%2Fgithub.com%2Falan-turing-institute%2Fsktime%22%2C+%22repo2docker.ref%22%3A+%22680edaa10f11f089d619be9086fa165fb6a2d151%22%7D: Internal Server Error ("Error processing tar file(exit status 1): write /sktime/datasets/data/PLAID/PLAID_TEST.ts: no space left on device")
```

??? Help?

**Comment by ZiyaoWei** [comment]
It seems a lot of people are experiencing this across different projects - https://discourse.jupyter.org/t/binder-launch-fails-with-oserror-errno-28-no-space-left-on-device/14530, so probably something on the Binder side.

Pointing directly to gesis works - https://gesis.mybinder.org/v2/gh/alan-turing-institute/sktime/main?filepath=examples/01_forecasting.ipynb, which helps support this theory.

**Comment by ZiyaoWei** [comment]
It seems the issues are fixed on Binder's end, closing.

**Comment by fkiraly** [comment]
ah, good to hear - I had run a binder at pydata and thought, maybe this is resolved, but somehow forgot to getting back to this issue. Thanks for following up, @ZiyaoWei!
