### ISSUE TITLE
[BUG] Error in Windows install related to conda install of pystan and prophet

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#2897]
**Describe the bug**
the recommended window install instructions recommend installing pystan and prophet from conda, due to ongoing problems with these dependencies.  have recently followed these successfully, but yesterday I tried a fresh install and got a dll error (which we have seen before, add links).

**To Reproduce**
conda create -n sktime python=3.8
conda activate sktime
conda install -c conda-forge pystan
conda install -c conda-forge prophet
pip install -e .[all_extras,dev] 

generates the following install error
Building wheels for collected packages: prophet
  Building wheel for prophet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\ajb\Anaconda3\envs\sktime-dev\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ajb\\AppData\\Local\\Temp\\pip-install-s9939hdp\\prophet_5f6254d3b43d4ee3b1849559ae7bc32a\\setup.py'"'"'; __file__='"'"'C:\\Users\\ajb\\AppData\\Local\\Temp\\pip-install-s9939hdp\\prophet_5f6254d3b43d4ee3b1849559ae7bc32a\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\ajb\AppData\Local\Temp\pip-wheel-wsmex1mz'
       cwd: C:\Users\ajb\AppData\Local\Temp\pip-install-s9939hdp\prophet_5f6254d3b43d4ee3b1849559ae7bc32a\
  Complete output (57 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\prophet
  creating build\lib\prophet\stan_model
  Importing plotly failed. Interactive plots will not work.
  --- Logging error ---
  Traceback (most recent call last):
    File "C:\Users\ajb\Anaconda3\envs\sktime-dev\lib\logging\__init__.py", line 1088, in emit
      stream.write(msg + self.terminator)
  ValueError: underlying buffer has been detached
  Call stack:
    File "<string>", line 1, in <module>
    File "C:\Users\ajb\AppData\Local\Temp\pip-install-s9939hdp\prophet_5f6254d3b43d4ee3b1849559ae7bc32a\setup.py", line 123, in <module>
      setup(
    File "C:\Users\ajb\Anaconda3\envs\sktime-dev\lib\site-packages\setuptools\__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\ajb\Anaconda3\envs\sktime-dev\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
      return run_commands(dist)
    File "C:\Users\ajb\Anaconda3\envs\sktime-dev\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
      dist.run_commands()
    File "C:\Users\ajb\Anaconda3\envs\sktime-dev\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "C:\Users\ajb\Anaconda3\envs\sktime-dev\lib\site-packages\setuptools\dist.py", line 1214, in run_command
      super().run_command(command)
    File "C:\Users\ajb\Anaconda3\envs\sktime-dev\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "C:\Users\ajb\Anaconda3\envs\sktime-dev\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Users\ajb\Anaconda3\envs\sktime-dev\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\ajb\Anaconda3\envs\sktime-dev\lib\site-packages\setuptools\dist.py", line 1214, in run_command
      super().run_command(command)
    File "C:\Users\ajb\Anaconda3\envs\sktime-dev\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "C:\Users\ajb\Anaconda3\envs\sktime-dev\lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\ajb\Anaconda3\envs\sktime-dev\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\ajb\Anaconda3\envs\sktime-dev\lib\site-packages\setuptools\dist.py", line 1214, in run_command
      super().run_command(command)
    File "C:\Users\ajb\Anaconda3\envs\sktime-dev\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "C:\Users\ajb\AppData\Local\Temp\pip-install-s9939hdp\prophet_5f6254d3b43d4ee3b1849559ae7bc32a\setup.py", line 48, in run
      build_models(target_dir)
    File "C:\Users\ajb\AppData\Local\Temp\pip-install-s9939hdp\prophet_5f6254d3b43d4ee3b1849559ae7bc32a\setup.py", line 38, in build_models
      StanBackendEnum.get_backend_class(backend).build_model(target_dir, MODEL_DIR)
    File "C:\Users\ajb\AppData\Local\Temp\pip-install-s9939hdp\prophet_5f6254d3b43d4ee3b1849559ae7bc32a\prophet\models.py", line 233, in build_model
      sm = pystan.StanModel(model_code=model_code)
    File "C:\Users\ajb\Anaconda3\envs\sktime-dev\lib\site-packages\pystan\model.py", line 259, in __init__
      logger.info(msg.format(self.model_name))
  Message: 'COMPILING THE C++ CODE FOR MODEL anon_model_f5236004a3fd5b8429270d00efcc0cf9 NOW.'
  Arguments: ()
  MSVC compiler is not supported
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for prophet
  Running setup.py clean for prophet
Failed to build prophet
Installing collected packages: urllib3, pyasn1, idna, charset-normalizer, toolz, rsa, requests, pyasn1-modules, oauthlib, numpy, locket, cachetools, tomli, threadpoolctl, sniffio, requests-oauthlib, pyyaml, py, pluggy, patsy, partd, MarkupSafe, llvmlite, joblib, iniconfig, heapdict, google-auth, fsspec, cloudpickle, attrs, atomicwrites, zict, wrapt, werkzeug, tzdata, tornado, tensorboard-plugin-wit, tensorboard-data-server, tblib, statsmodels, sortedcontainers, scikit-learn, rfc3986, pytest, pyluach, psutil, protobuf, platformdirs, numba, msgpack, markdown, lunardate, jinja2, h11, grpcio, google-auth-oauthlib, filelock, distlib, dask, coverage, click, backports.zoneinfo, anyio, absl-py, workalendar, virtualenv, toml, termcolor, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard, stumpy, seaborn, pytest-forked, pmdarima, opt-einsum, nodeenv, matrixprofile, libclang, keras-preprocessing, keras, identify, httpcore, h5py, google-pasta, gast, flatbuffers, execnet, dm-tree, distributed, deprecated, decorator, cmdstanpy, cfgv, astunparse, tslearn, tsfresh, tensorflow-probability, tensorflow, tbats, statsforecast, sktime, scikit-posthocs, pytest-xdist, pytest-timeout, pytest-cov, pyod, pykalman, prophet, pre-commit, httpx, hcrystalball, filterpy, esig, dtw-python
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.0
    Uninstalling numpy-1.23.0:
      Successfully uninstalled numpy-1.23.0
  Attempting uninstall: cmdstanpy
    Found existing installation: cmdstanpy 1.0.2
    Uninstalling cmdstanpy-1.0.2:
      Successfully uninstalled cmdstanpy-1.0.2
  Running setup.py develop for sktime
  Attempting uninstall: prophet
    Found existing installation: prophet 1.1
    Uninstalling prophet-1.1:
      Successfully uninstalled prophet-1.1
    Running setup.py install for prophet ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\ajb\Anaconda3\envs\sktime-dev\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ajb\\AppData\\Local\\Temp\\pip-install-s9939hdp\\prophet_5f6254d3b43d4ee3b1849559ae7bc32a\\setup.py'"'"'; __file__='"'"'C:\\Users\\ajb\\AppData\\Local\\Temp\\pip-install-s9939hdp\\prophet_5f6254d3b43d4ee3b1849559ae7bc32a\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ajb\AppData\Local\Temp\pip-record-8g8e_y2n\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\ajb\Anaconda3\envs\sktime-dev\Include\prophet'
         cwd: C:\Users\ajb\AppData\Local\Temp\pip-install-s9939hdp\prophet_5f6254d3b43d4ee3b1849559ae7bc32a\
    Complete output (11 lines):
    running install
    C:\Users\ajb\Anaconda3\envs\sktime-dev\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\prophet
    creating build\lib\prophet\stan_model
    Importing plotly failed. Interactive plots will not work.
    error: Could not find module 'C:\Users\ajb\Anaconda3\envs\sktime-dev\lib\site-packages\scipy\.libs\libbanded5x.R5FKBI2I62BSXV4Z4HDB42UEWJ6S2M5F.gfortran-win_amd64.dll' (or one of its dependencies). Try using the full path with constructor syntax.
    ----------------------------------------
  Rolling back uninstall of prophet
  Moving to c:\users\ajb\anaconda3\envs\sktime-dev\lib\site-packages\prophet-1.1.dist-info\
   from C:\Users\ajb\Anaconda3\envs\sktime-dev\Lib\site-packages\~rophet-1.1.dist-info
  Moving to c:\users\ajb\anaconda3\envs\sktime-dev\lib\site-packages\prophet\
   from C:\Users\ajb\Anaconda3\envs\sktime-dev\Lib\site-packages\~rophet
ERROR: Command errored out with exit status 1: 'C:\Users\ajb\Anaconda3\envs\sktime-dev\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ajb\\AppData\\Local\\Temp\\pip-install-s9939hdp\\prophet_5f6254d3b43d4ee3b1849559ae7bc32a\\setup.py'"'"'; __file__='"'"'C:\\Users\\ajb\\AppData\\Local\\Temp\\pip-install-s9939hdp\\prophet_5f6254d3b43d4ee3b1849559ae7bc32a\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ajb\AppData\Local\Temp\pip-record-8g8e_y2n\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\ajb\Anaconda3\envs\sktime-dev\Include\prophet' Check the logs for full command output.

this is different to yesterday, when installed ok, but creates the following error when running some code

FileNotFoundError: Could not find module 'C:\Users\ajb\Anaconda3\envs\sktime\lib\site-packages\scipy\.libs\libbanded5x.R5FKBI2I62BSXV4Z4HDB42UEWJ6S2M5F.gfortran-win_amd64.dll' (or one of its dependencies). Try using the full path with constructor syntax.

with the following trace back when executing the following code
C:\Users\ajb\Anaconda3\envs\sktime\python.exe C:/code/sktime/sktime/_contrib/clustering_experiments.py
Traceback (most recent call last):
  File "C:/code/sktime/sktime/_contrib/clustering_experiments.py", line 18, in <module>
    import sklearn.metrics
  File "C:\Users\ajb\Anaconda3\envs\sktime\lib\site-packages\sklearn\__init__.py", line 82, in <module>
    from .base import clone
  File "C:\Users\ajb\Anaconda3\envs\sktime\lib\site-packages\sklearn\base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "C:\Users\ajb\Anaconda3\envs\sktime\lib\site-packages\sklearn\utils\__init__.py", line 22, in <module>
    from scipy.sparse import issparse
  File "C:\Users\ajb\Anaconda3\envs\sktime\lib\site-packages\scipy\__init__.py", line 136, in <module>
    from . import _distributor_init
  File "C:\Users\ajb\Anaconda3\envs\sktime\lib\site-packages\scipy\_distributor_init.py", line 59, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Users\ajb\Anaconda3\envs\sktime\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)

**Versions**
<details>
the environment is this

(sktime-dev) C:\code\test\sktime>conda list
# packages in environment at C:\Users\ajb\Anaconda3\envs\sktime-dev:
#
# Name                    Version                   Build  Channel
absl-py                   1.1.0                    pypi_0    pypi
anyio                     3.6.1                    pypi_0    pypi
arviz                     0.12.1             pyhd8ed1ab_0    conda-forge
astunparse                1.6.3                    pypi_0    pypi
atomicwrites              1.4.0                    pypi_0    pypi
attrs                     21.4.0                   pypi_0    pypi
backports-zoneinfo        0.2.1                    pypi_0    pypi
brotli                    1.0.9                h8ffe710_7    conda-forge
brotli-bin                1.0.9                h8ffe710_7    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.6.15            h5b45459_0    conda-forge
cachetools                5.2.0                    pypi_0    pypi
certifi                   2022.6.15        py38haa244fe_0    conda-forge
cfgv                      3.3.1                    pypi_0    pypi
cftime                    1.6.0            py38hbdcd294_1    conda-forge
charset-normalizer        2.0.12                   pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
cloudpickle               2.1.0                    pypi_0    pypi
cmdstan                   2.29.2               hc4b6281_2    conda-forge
cmdstanpy                 0.9.68                   pypi_0    pypi
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
convertdate               2.4.0              pyhd8ed1ab_0    conda-forge
coverage                  6.4.1                    pypi_0    pypi
curl                      7.83.1               h789b8ee_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.30          py38h885f38d_0    conda-forge
dask                      2022.6.1                 pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
deprecated                1.2.13                   pypi_0    pypi
distlib                   0.3.4                    pypi_0    pypi
distributed               2022.6.1                 pypi_0    pypi
dm-tree                   0.1.7                    pypi_0    pypi
ephem                     4.1.3            py38h294d835_4    conda-forge
execnet                   1.9.0                    pypi_0    pypi
filelock                  3.7.1                    pypi_0    pypi
flatbuffers               1.12                     pypi_0    pypi
fonttools                 4.33.3           py38h294d835_0    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
fsspec                    2022.5.0                 pypi_0    pypi
gast                      0.4.0                    pypi_0    pypi
google-auth               2.9.0                    pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.47.0                   pypi_0    pypi
h11                       0.12.0                   pypi_0    pypi
h5py                      3.7.0                    pypi_0    pypi
hdf4                      4.2.15               h0e5069d_3    conda-forge
hdf5                      1.12.1          nompi_h2a0e4a3_104    conda-forge
heapdict                  1.0.1                    pypi_0    pypi
hijri-converter           2.2.4              pyhd8ed1ab_0    conda-forge
holidays                  0.13               pyhd8ed1ab_0    conda-forge
httpcore                  0.15.0                   pypi_0    pypi
identify                  2.5.1                    pypi_0    pypi
idna                      3.3                      pypi_0    pypi
importlib-metadata        4.11.4           py38haa244fe_0    conda-forge
importlib_metadata        4.11.4               hd8ed1ab_0    conda-forge
iniconfig                 1.1.1                    pypi_0    pypi
intel-openmp              2022.1.0          h57928b3_3787    conda-forge
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9e                   h8ffe710_1    conda-forge
keras                     2.9.0                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.4.3            py38hbd9d945_0    conda-forge
korean_lunar_calendar     0.2.1              pyh9f0ad1d_0    conda-forge
krb5                      1.19.3               h1176d77_0    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libblas                   3.9.0              15_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h8ffe710_7    conda-forge
libbrotlidec              1.0.9                h8ffe710_7    conda-forge
libbrotlienc              1.0.9                h8ffe710_7    conda-forge
libcblas                  3.9.0              15_win64_mkl    conda-forge
libclang                  14.0.1                   pypi_0    pypi
libcurl                   7.83.1               h789b8ee_0    conda-forge
libdeflate                1.12                 h8ffe710_0    conda-forge
liblapack                 3.9.0              15_win64_mkl    conda-forge
libnetcdf                 4.8.1           nompi_h1cc8e9d_102    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libpython                 2.2              py38haa244fe_1    conda-forge
libssh2                   1.10.0               h680486a_2    conda-forge
libtiff                   4.4.0                h2ed3b44_1    conda-forge
libwebp                   1.2.2                h57928b3_0    conda-forge
libwebp-base              1.2.2                h8ffe710_1    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libzip                    1.9.2                hfed4ece_0    conda-forge
libzlib                   1.2.12               h8ffe710_1    conda-forge
llvmlite                  0.38.1                   pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
lunarcalendar             0.0.9                      py_0    conda-forge
lunardate                 0.2.0                    pypi_0    pypi
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2-bash                   4.3.042                       5    conda-forge
m2-coreutils              8.25                        102    conda-forge
m2-filesystem             2016.04                       4    conda-forge
m2-gcc-libs               5.3.0                         4    conda-forge
m2-gmp                    6.1.0                         3    conda-forge
m2-libiconv               1.14                          3    conda-forge
m2-libintl                0.19.7                        4    conda-forge
m2-msys2-runtime          2.5.0.17080.65c939c               3    conda-forge
m2-sed                    4.2.2                         3    conda-forge
m2w64-binutils            2.25.1                        5    conda-forge
m2w64-bzip2               1.0.6                         6    conda-forge
m2w64-crt-git             5.0.0.4636.2595836               2    conda-forge
m2w64-gcc                 5.3.0                         6    conda-forge
m2w64-gcc-ada             5.3.0                         6    conda-forge
m2w64-gcc-fortran         5.3.0                         6    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gcc-objc            5.3.0                         6    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-headers-git         5.0.0.4636.c0ad18a               2    conda-forge
m2w64-isl                 0.16.1                        2    conda-forge
m2w64-libiconv            1.14                          6    conda-forge
m2w64-libmangle-git       5.0.0.4509.2e5a9a2               2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
m2w64-make                4.1.2351.a80a8b8               2    conda-forge
m2w64-mpc                 1.0.3                         3    conda-forge
m2w64-mpfr                3.1.4                         4    conda-forge
m2w64-pkg-config          0.29.1                        2    conda-forge
m2w64-toolchain           5.3.0                         7    conda-forge
m2w64-toolchain_win-64    2.4.0                         0    conda-forge
m2w64-tools-git           5.0.0.4592.90b8472               2    conda-forge
m2w64-windows-default-manifest 6.4                           3    conda-forge
m2w64-winpthreads-git     5.0.0.4634.697f757               2    conda-forge
m2w64-zlib                1.2.8                        10    conda-forge
markdown                  3.3.7                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib-base           3.5.2            py38he529843_0    conda-forge
matrixprofile             1.1.10                   pypi_0    pypi
mkl                       2022.1.0           h6a75c08_874    conda-forge
msgpack                   1.0.4                    pypi_0    pypi
msys2-conda-epoch         20160418                      1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
netcdf4                   1.5.8           nompi_py38h0500770_101    conda-forge
nodeenv                   1.7.0                    pypi_0    pypi
numba                     0.55.2                   pypi_0    pypi
numpy                     1.21.6                   pypi_0    pypi
oauthlib                  3.2.0                    pypi_0    pypi
openjpeg                  2.4.0                hb211442_1    conda-forge
openssl                   1.1.1p               h8ffe710_0    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.3            py38hcc40339_0    conda-forge
partd                     1.2.0                    pypi_0    pypi
patsy                     0.5.2                    pypi_0    pypi
pillow                    9.1.1            py38hd8e0db4_1    conda-forge
pip                       21.2.2           py38haa95532_0
platformdirs              2.5.2                    pypi_0    pypi
pluggy                    1.0.0                    pypi_0    pypi
pmdarima                  1.8.5                    pypi_0    pypi
prophet                   1.1              py38haa244fe_1    conda-forge
protobuf                  3.11.2                   pypi_0    pypi
psutil                    5.9.1                    pypi_0    pypi
pthread-stubs             0.4               hcd874cb_1001    conda-forge
py                        1.11.0                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pykalman                  0.9.5                    pypi_0    pypi
pyluach                   2.0.0                    pypi_0    pypi
pymeeus                   0.5.10             pyhd8ed1ab_0    conda-forge
pyod                      1.0.2                    pypi_0    pypi
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pystan                    2.19.1.1         py38h02adce6_3    conda-forge
pytest                    7.1.2                    pypi_0    pypi
pytest-cov                3.0.0                    pypi_0    pypi
pytest-forked             1.4.0                    pypi_0    pypi
pytest-timeout            2.1.0                    pypi_0    pypi
pytest-xdist              2.5.0                    pypi_0    pypi
python                    3.8.13               h6244533_0
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0                      pypi_0    pypi
requests                  2.28.0                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rfc3986                   1.5.0                    pypi_0    pypi
rsa                       4.8                      pypi_0    pypi
scikit-learn              1.1.1                    pypi_0    pypi
scikit-posthocs           0.7.0                    pypi_0    pypi
scipy                     1.8.1            py38h9bf8e03_0    conda-forge
seaborn                   0.11.2                   pypi_0    pypi
setuptools                61.2.0           py38haa95532_0
setuptools-git            1.2                        py_1    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sktime                    0.12.1                    dev_0    <develop>
sniffio                   1.2.0                    pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
sqlite                    3.38.5               h2bbff1b_0
statsforecast             0.5.6                    pypi_0    pypi
statsmodels               0.13.2                   pypi_0    pypi
stumpy                    1.11.1                   pypi_0    pypi
tbats                     1.1.0                    pypi_0    pypi
tbb                       2021.5.0             h2d74725_1    conda-forge
tblib                     1.7.0                    pypi_0    pypi
tensorboard               2.9.1                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.9.1                    pypi_0    pypi
tensorflow-estimator      2.9.0                    pypi_0    pypi
tensorflow-io-gcs-filesystem 0.26.0                   pypi_0    pypi
tensorflow-probability    0.17.0                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.12               h8ffe710_0    conda-forge
toml                      0.10.2                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.11.2                   pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
tsfresh                   0.19.0                   pypi_0    pypi
tslearn                   0.5.2                    pypi_0    pypi
typing_extensions         3.10.0.2           pyha770c72_0    conda-forge
tzdata                    2022.1                   pypi_0    pypi
ujson                     5.3.0            py38h885f38d_0    conda-forge
unicodedata2              14.0.0           py38h294d835_1    conda-forge
urllib3                   1.26.9                   pypi_0    pypi
vc                        14.2                 h21ff451_1
virtualenv                20.15.1                  pypi_0    pypi
vs2015_runtime            14.27.29016          h5e58377_2
werkzeug                  2.1.2                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0
wincertstore              0.2              py38haa95532_2
workalendar               16.3.0                   pypi_0    pypi
wrapt                     1.14.1                   pypi_0    pypi
xarray                    2022.3.0           pyhd8ed1ab_0    conda-forge
xarray-einstats           0.3.0              pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
zict                      2.2.0                    pypi_0    pypi
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h8ffe710_1    conda-forge
zstd                      1.5.2                h6255e5f_1    conda-forge

</details>

**Comment by aiwalter** [comment]
should be fixed by #2887

**Comment by TonyBagnall** [comment]
I'll test drive it again once #2887 gets merged

**Comment by TonyBagnall** [comment]
fixed by #2887 , tested on two window boxes
