### ISSUE TITLE
[BUG] ERROR: Couldn't install package: sktime

### ISSUE THREAD

**Issue by 4d30** [alan-turing-institute/sktime#3247]
**Describe the bug**
sktime cannot be installed.

`python setup.py egg_info `does not run successfully. There are multiple top-level packages discovered in a flat-layout: ['sktime', 'build_tools', 'extension_templates']

**To Reproduce**
Attempt an install of sktime

```
$ pipenv install sktime
```

```shell
$ pipenv install sktime                                                                                                                                                           [45/324]
Installing sktime...                                                                                                                                                                           
Adding sktime to Pipfile's [packages]...                                                                                                                                                       
✔ Installation Succeeded                                                                                                                                                                       
Installing dependencies from Pipfile.lock (ad0018)...                                                                                                                                          
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 2/2 — 00:00:00                          
An error occurred while installing sktime==0.8.0 --hash=sha256:dc17e38eeb5d00361b42386c781ed56441134f859c120a4e4b1b030f87ae00d8 --hash=sha256:c0c99eebfccdd8ec603ecfc61aac4d9dca3e1d307b82920de
2a5bcd3cf8453b4 --hash=sha256:396216ea7fb63c5c611c38f140212a9d4976608bd55f8bbccd78ba5df7e70727 --hash=sha256:60f066de8a54318f29a5fb9b19ca8e73d67c69529c0fb318cfae9357a6c21247 --hash=sha256:657
0ad33794dbb49ec78f891e51195d48b45091d2776072def4c995e0e3b5603 --hash=sha256:9f5418f1c1d1d7b0d32ba03890d9ed67f7416be17cb575894bbf6faca6d09af1 --hash=sha256:764dc1254b75e4f42907320eb67e75d734e9
73704f70bf508748cbeb59ba6b14 --hash=sha256:2df1185e045c9927e0deaa7ec7e6e56012df999ce9e382162a12f39d569a020e --hash=sha256:8970f2d4f2eb54c0181b05f5714d198a0fa95c127252475e5216a702347cd881 --ha
sh=sha256:8c7e27ea93bfcbf90b0d813ed5ec992649624936af2853045eb0bffc0eb5522f --hash=sha256:bb9c97b9f77f140ccf495f412068e842193091e9ac0122e21aca709c02325e3d --hash=sha256:f35ab884a456ce7eea61d0b
d20527cf389ab7b1ae7c04ebad9b9025b8fee02ae --hash=sha256:6debacac87cf4ce6a89691c16e8a93c6dd22bfe42ef9156bf1869f2bc84acc4e --hash=sha256:91fad9b80eb5d986226265594961a8198f67cf05e2a7e75f2e790458
cef400ef --hash=sha256:15a629df60f7512c37e5f7391e19039a3bcf75fd6dc96ec6b158ff453fa7ca0d --hash=sha256:25ad30cd6c6167ddb9dee90114df7ecb8b4518a9df9e2eaa83580c79930ac037! Will try again.
Installing initially failed dependencies...
[pipenv.exceptions.InstallError]: Collecting sktime==0.8.0                                                                                                                                     
[pipenv.exceptions.InstallError]:   Using cached sktime-0.8.0.tar.gz (9.7 MB)
[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): started                                                                                                                     
[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): finished with status 'error' 
[pipenv.exceptions.InstallError]: error: subprocess-exited-with-error                                                                                                                          
[pipenv.exceptions.InstallError]:   
[pipenv.exceptions.InstallError]:   × python setup.py egg_info did not run successfully.                                                                                                       
[pipenv.exceptions.InstallError]:   │ exit code: 1   
[pipenv.exceptions.InstallError]:   ╰─> [16 lines of output]                                                                                                                                   
[pipenv.exceptions.InstallError]:       /home/user/.local/share/virtualenvs/pdva-VEwz2__Q/lib/python3.10/site-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'descrip
tion-file' will not be supported in future versions. Please use the underscore name 'description_file' instead                                                 
[pipenv.exceptions.InstallError]:         warnings.warn(
[pipenv.exceptions.InstallError]:       error: Multiple top-level packages discovered in a flat-layout: ['sktime', 'build_tools', 'extension_templates'].
[pipenv.exceptions.InstallError]:            
[pipenv.exceptions.InstallError]:       To avoid accidental inclusion of unwanted files or directories,                                 
[pipenv.exceptions.InstallError]:       setuptools will not proceed with this build.
[pipenv.exceptions.InstallError]:                                                                                                                                                              
[pipenv.exceptions.InstallError]:       If you are trying to create a single distribution with multiple packages
[pipenv.exceptions.InstallError]:       on purpose, you should not rely on automatic discovery.                                             
[pipenv.exceptions.InstallError]:       Instead, consider the following options:
[pipenv.exceptions.InstallError]:                                                                                                                                                              
[pipenv.exceptions.InstallError]:       1. set up custom discovery (`find` directive with `include` or `exclude`)
[pipenv.exceptions.InstallError]:       2. use a `src-layout`
[pipenv.exceptions.InstallError]:       3. explicitly set `py_modules` or `packages` with a list of names
[pipenv.exceptions.InstallError]:           
[pipenv.exceptions.InstallError]:       To find more information, look for "package discovery" on setuptools docs.
[pipenv.exceptions.InstallError]:       [end of output]                    
[pipenv.exceptions.InstallError]:   
[pipenv.exceptions.InstallError]:   note: This error originates from a subprocess, and is likely not a problem with pip.
[pipenv.exceptions.InstallError]: error: metadata-generation-failed
[pipenv.exceptions.InstallError]: 
[pipenv.exceptions.InstallError]: × Encountered error while generating package metadata.
[pipenv.exceptions.InstallError]: ╰─> See above for output.
[pipenv.exceptions.InstallError]: 
[pipenv.exceptions.InstallError]: note: This is an issue with the package mentioned above, not pip.
[pipenv.exceptions.InstallError]: hint: See above for details.
ERROR: Couldn't install package: sktime

```

**Expected behavior**

It is expected that sktime installs without issue.

**Additional context**

This might be relevant:
[https://github.com/nucleic/kiwi/issues/130](https://github.com/nucleic/kiwi/issues/130)

**Versions**
$ uname -a 
Linux localhost 4.18.0-25-generic #26~18.04.1-Ubuntu SMP Thu Jun 27 07:28:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
(pdva) localhost$ python -V
Python 3.10.0
$ pipenv --version
pipenv, version 2022.4.20

</details>

**Comment by fkiraly** [comment]
Hm, it looks like:

* you are using an outdated version of `sktime`. Current is 0.13.1, your version is 0.8.0.
* you are not following the recommended install workflow via `pip`, for developer install, see https://www.sktime.org/en/stable/installation.html#development-versions

**Comment by 4d30** [comment]
@fkiraly I don't know exactly what's happened. It appears as though, with some more digging, sktime==0.13.1 is installed despite this error message.

Remarkably if setuptools is not imported before before sktime, then there are adverse effects.

```
$ pipenv run python
Python 3.10.0 (default, Apr 27 2022, 14:04:53) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>> from sktime import show_versions; show_versions()
/home/jmifsud/.local/share/virtualenvs/pdva-VEwz2__Q/lib/python3.10/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

System:
    python: 3.10.0 (default, Apr 27 2022, 14:04:53) [GCC 7.5.0]
executable: /home/jmifsud/.local/share/virtualenvs/pdva-VEwz2__Q/bin/python
   machine: Linux-4.18.0-25-generic-x86_64-with-glibc2.27

Python dependencies:
          pip: 22.0.4
   setuptools: 64.0.1
      sklearn: 1.1.2
       sktime: 0.13.1
  statsmodels: 0.13.2
        numpy: 1.22.4
        scipy: 1.9.0
       pandas: 1.4.3
   matplotlib: 3.5.3
       joblib: 1.1.0
        numba: 0.56.0
     pmdarima: None
      tsfresh: 0.19.0

```

Closing issue, thank you for your time.

**Comment by fkiraly** [comment]
That´s odd, @4d30 - do you get the error if you try to install sktime 0.13.1?

If so, there might be a bug here worth investiating!

**Comment by 4d30** [comment]
@fkiraly  If  sktime==0.13.1 is explicitly set, then installation proceeds all nicey-nice. 

If setuptools is not imported before sktime, an AssertionError is thrown for this install:

```
$ pipenv run python
Python 3.10.0 (default, Apr 27 2022, 14:04:53) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sktime import show_versions; show_versions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/share/virtualenvs/pdva-VEwz2__Q/lib/python3.10/site-packages/sktime/utils/_maint/_show_versions.py", line 85, in show_versions
    deps_info = _get_deps_info()
  File "/home/user/.local/share/virtualenvs/pdva-VEwz2__Q/lib/python3.10/site-packages/sktime/utils/_maint/_show_versions.py", line 73, in _get_deps_info
    mod = importlib.import_module(modname)
  File "/home/user/.local/pyenv/versions/3.10.0/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jmifsud/.local/share/virtualenvs/pdva-VEwz2__Q/lib/python3.10/site-packages/setuptools/__init__.py", line 8, in <module>
    import _distutils_hack.override  # noqa: F401
  File "/home/user/.local/share/virtualenvs/pdva-VEwz2__Q/lib/python3.10/site-packages/_distutils_hack/override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "/home/user/.local/share/virtualenvs/pdva-VEwz2__Q/lib/python3.10/site-packages/_distutils_hack/__init__.py", line 77, in do_override
    ensure_local_distutils()
  File "/home/user/.local/share/virtualenvs/pdva-VEwz2__Q/lib/python3.10/site-packages/_distutils_hack/__init__.py", line 64, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
AssertionError: /home/user/.local/pyenv/versions/3.10.0/lib/python3.10/distutils/core.py
```

The knowledge of building python packages is a moving target that I've not spent much time learning about. Probably has to do with this thing called **_distutils_hack**
