### ISSUE TITLE
[BUG] `self._check_fh(fh)` failure in `predict_residuals` for estimators with `"requires-fh-in-fit": True`

### ISSUE THREAD

**Issue by kcc-lion** [alan-turing-institute/sktime#3479]
**Describe the bug**

This is a potential bug occurring when `predict_residuals` is called for forecasters with `requires-fh-in-fit=True`. This is caused by a discrepancy in the `fh` inferred by `predict_residuals` and `self.fh` which is derived from the `fh` in `fit`.

Example:
Fit a forecaster with e.g. a  fh of `ForecastingHorizon([1], dtype='int64', is_relative=True)` to a `y` that gives `self.cutoff=52`. Then, calling `predict_residuals` with `y: (5, 1.0)` creates a forecasting horizon that does not match the one that was passed in fit, causing `self._check_fh(fh)` to fail. In the example above, `predict_residuals` would generate fh as `ForecastingHorizon([-47], dtype='int64', is_relative=True)` which does not match the `fh` seen in fit, which causes the failure in `self._check_fh(fh)`.

This failure is possibly related to #3475.

**To Reproduce**

The gist below contains an implementation of an estimator that requires fh in fit and implements `predict_residuals`:
https://gist.github.com/kcc-lion/9d77bf0820db0ccac114e8933295200e

To replicate, one can alternatively take any estimator that requires `fh` in fit and does not return a `NotImplementedError` for `predict_residuals` and run 

```python
from sktime.forecasting.example import ExampleEstimator
from sktime.utils.estimator_checks import check_estimator
check_estimator(ExampleEstimator, fixtures_to_run='test_predict_residuals[ExampleEstimator-y:1cols-fh=1-int-int-True]', return_exceptions=False)
```

To the best of my knowledge, there is no such estimator which requires `fh` in fit and does not return a `NotImplementedError` for `predict_residuals`. This is why the above code snippet uses `ExampleEstimator` as a placeholder for such an estimator.

**Expected behavior**

Expected behavior would be that `self._check_fh(fh)` does not fail for in-sample prediction to generate residuals.

**Additional context**

The traceback looks as follows:
```
Traceback (most recent call last):
  File "/Users/kai/Desktop/repos/sktime/sktime/forecasting/tests/test_all_forecasters.py", line 262, in test_predict_residuals
    y_res = estimator_instance.predict_residuals(y_test)
  File "/Users/kai/Desktop/repos/sktime/sktime/forecasting/base/_base.py", line 1078, in predict_residuals
    fh = self._check_fh(fh)
  File "/Users/kai/Desktop/repos/sktime/sktime/forecasting/base/_base.py", line 1634, in _check_fh
    raise ValueError(
ValueError: A different forecasting horizon `fh` has been provided from the one seen in `fit`. If you want to change the forecasting horizon, please re-fit the forecaster. This is because fitting of the `SquaringResiduals` depends on `fh`. 
```
**Versions**
<details>

</details>

**Comment by aiwalter** [comment]
Hi @kcc-lion , I think i understand the issue here and I will include a fix for i in my recent related PR #3475

**Comment by aiwalter** [comment]
I have seen that actually its mentioned how to deal with `fh` required in  `fit`:
https://github.com/alan-turing-institute/sktime/blob/e5b30e8168e572b80b8ac608a8022c64808f946b/sktime/forecasting/base/_base.py#L1031

So its a known issue. It can be resolved by using `deepcopy` and fitting the copy of `self` again with the in-sample `fh`. Do you want to work on that @kcc-lion ? I decided to first get my other PR merged.

**Comment by davidgilbertson** [comment]
This appears to break `ReconcilerForecster` too. The snippet from the docs (which only uses `y`) works, but I can't get it to work with `X` and `y`. This is where it creates the mismatching `fh`.

https://github.com/sktime/sktime/blob/0d9d1a54cacaa0e6e65cd884806e5f9fbe6e0f12/sktime/forecasting/reconcile.py#L174-L178

But this only occurs for the methods `mint_cov`, `mint_shrink` and `wls_var`.

**Comment by fkiraly** [comment]
@davidgilbertson, what should be the default behaviour here?

Given that the forecaster requires `fh` already in `fit`, you would have to tell it at that point in time that you intend `fh` to be what you pass in `predict_residuals`.

Should it re-fit the forecaster in `predict_residuals`?

**Comment by davidgilbertson** [comment]
Let me preface my response by saying I don't really get what `ReconcilerForecaster` does, I'm just now learning about it. Maybe it doesn't make sense to do this sort of reconciliation when the forecaster is an ML model (since the in-sample predictions are really just a measure of the model's ability to memorize the data it's seen). Is this intended more for things like ETS and ARIMA?

**Comment by fkiraly** [comment]
> Maybe it doesn't make sense to do this sort of reconciliation when the forecaster is an ML model

It does make methodological sense imo, as in-sample predictions from ML models do not agree, in general, with the actuals.

I would see the problem being with the old `make_reduction` which can't make in-sample forecasts.

With the new reduction estimator, it should not be a problem (the problem is runtime, although we're getting there! see the draft PR if you have any time to spare to help with the runtime optimisation)

**Comment by davidgilbertson** [comment]
I tweaked the code a bit from this:
```py
self.residuals_ = y - self.forecaster_.predict(fh=fh_resid, X=X)
```
To this:
```py
forecaster_resid = self.forecaster_.clone().fit(y=y, X=X, fh=fh_resid)
self.residuals_ = y - forecaster_resid.predict(fh=fh_resid, X=X)
```

And it at least runs. But my forecaster is a pipeline wrapper around an ML model and my data is two years of daily data per instance, so this ends up being a prediction with a two year horizon starting at day 1, lagging the prediction value into X at each step. So errors tend to accumulate and I wonder if this makes the `residuals` indicative of anything meaningful. Would it make more sense to do a one-step forecast for each time step? That would also be much faster. Is this what you mean about the new reduction estimator being able to do in-sample forecasts?

FYI I can't get any reconciliation method to outperform a baseline and I'm wondering if it's just never going to work for my particular setup (plenty of data in each instance, training one model per instance, only interested in the leaf-level results) or if it _could_ be better but there's just one little thing that's not quite right somewhere (like the residuals not being indicative of the abilities of the model)

**Comment by fkiraly** [comment]
> I tweaked the code a bit from this:

Yes, I see!

I would appreciate a PR where you:

* check that `fh_resid` is different from current `fh` (`self._fh`)
* if yes, run your code
* if no, run the original code
* add a test for same and different

Optionally:
* check if you can run original if `fh_resid` is different from current `fh`, and `requires-fh-in-fit` tag is `False`
* if that's fine, adapt the above

Let us know if you would like to add this or not - given that you've already done this locally, it's probably best if you do it though?

> So errors tend to accumulate and I wonder if this makes the residuals indicative of anything meaningful. Would it make more sense to do a one-step forecast for each time step? That would also be much faster. Is this what you mean about the new reduction estimator being able to do in-sample forecasts?

Yes!

> FYI I can't get any reconciliation method to outperform a baseline

Do you mean, it doesn't outperform the same forecaster *without* reconciliation?

There's two levers you can adjust here:

* the forecaster that does the heavy lifting
* whether you do reconciliation or not, if yes using which method

So, do you mean:

1. you have forecaster `f`, and it does not get better when you add reconciliation
2. your combined forecaster `f`-plus-reconciler is not better than `NaiveForecaster` without `sp`?

If you mean 1., that is actually normal - on smaller amounts of hierarchy levels, reconciliation only ensures that levels add up, it doesn't necessarily need to make the forecast better.

This is similar to the common pseudo-paradox where you try to predict a quantity that you know is an integer - and, in terms of MSE, predicting a non-integer will in general be optimal above a prediction that you force to be integer.
(simple example: let's assume you predict a quantity that can be any integer between 0 and 100, and usually is around 50. The best prediction as measured by MSE is the expected value of the true distribution, which is in general not an integer)

**Comment by davidgilbertson** [comment]
Yes I meant 1. Good to hear it's normal, thanks for that.

**Comment by fkiraly** [comment]
> Good to hear it's normal, thanks for that.

Well, it depends, but it is not "normal" as you would always expect it, but it wouldn't be unusual.

There are two extremes here:

* your forecasters are already as good as can be (compared to sample size, noise, etc), and the forecasting noise is highly correlated, so "sharing information" via the reconciler doesn't give you much of an additional edge
* your forecasts are extremely noisy and/or you have a large sample size; the "power" so to speak lives all in trying to average out the noise between the different hierarchy nodes. A contrived math example would be, your forecasts have zero bias, but enormous variance, and said variance is independent between the hierarchy instances.

It also depends on how you measure the goodness of your hierarchical forecast - in a contrived example of a metric, you could penalize that forecasts "don't add up", but this also can work more subtly in or against your favour.

**Comment by benHeid** [comment]
This is still an issue. It is also affecting other forecasters such as AutoTS, ...

It can be reproduced by:

```python
import numpy as np
import pandas as pd

from sktime.forecasting.base import BaseForecaster, ForecastingHorizon


class RequiresFhInFitForecaster(BaseForecaster):
    """Minimal forecaster requiring fh at fit time, mirroring the issue's repro gist."""

    _tags = {
        "requires-fh-in-fit": True,
        "y_inner_mtype": "pd.Series",
        "scitype:y": "univariate",
        "ignores-exogeneous-X": True,
    }

    def _fit(self, y, X=None, fh=None):
        self._y_fit = y
        return self

    def _predict(self, fh, X=None):
        last_val = self._y_fit.iloc[-1]
        index = fh.to_absolute(self.cutoff).to_pandas()
        return pd.Series(last_val, index=index)


# small synthetic dataset, no network access needed
y = pd.Series(np.arange(50, dtype=float), index=pd.RangeIndex(50))

fh = ForecastingHorizon([1], is_relative=True)

forecaster = RequiresFhInFitForecaster()
forecaster.fit(y, fh=fh)

print(f"Fitted forecaster with fh={fh}, cutoff={forecaster.cutoff}")

bug_present = False
error_message = None
residuals = None
try:
    residuals = forecaster.predict_residuals(y)
except ValueError as e:
    bug_present = True
    error_message = str(e)

if bug_present:
    print(f"predict_residuals raised ValueError: {error_message}")
else:
    print(f"predict_residuals succeeded, returned residuals of length {len(residuals)}")

assert not bug_present, (
    "predict_residuals() raised a ValueError due to a mismatch between the "
    "in-sample fh it constructs internally and the fh stored from fit(), for a "
    "forecaster with the 'requires-fh-in-fit' tag set to True. Expected behavior "
    "(per the issue) is that this in-sample residual computation does not fail. "
    f"Original error: {error_message}"
)

assert isinstance(residuals, pd.Series), "predict_residuals should return a pd.Series"
assert len(residuals) == len(y), (
    f"Expected residuals to align with the {len(y)} observations in y, "
    f"got {len(residuals)}"
)

```

Triaged with Claude Code
