### ISSUE TITLE
[ENH] design discussion - `fh` related contract if passed in both `fit` and `predict`

### ISSUE THREAD

**Issue by yarnabrina** [alan-turing-institute/sktime#4698]
update by @fkiraly: the below is mainly a design discussion related to the `BaseForecaster` contract in a case where both `fit` and `predict` have a non-trivial `fh` argument passed, specifically in some cases where the user might expect different behaviour from status quo.

The behaviour of `ForecastX` is a special case, in fact all forecasters behave like that. (it is non-obvious from the example that it is a special case that generalizes)
That special behaviour is particularly unintuitive for `ForecastX` though, more obviously so than for other forecasters.

---

original post by @yarnabrina:

---

As of now, `ForecastX` seems to allow prediction with only the identical `fh` provided in `fit` or a permutation of it, and of nothing else. Even a subset of the fit fails, so does in-sample predictions.

For example, the following composite estimator is trained with `fh=[1, 2, 3]`. As an user, I expect to be able to predict for just `1` or just `[2, 3]` etc., as these observations must be already predicted by `forecaster_X`. Also, since the `fit` already contained the training data for `X`, I expect to be able to predict in-sample for all (negative) horizons. However, both of these cases fail.

## Reproducible Example

```python3
from sktime.datasets import load_longley
from sktime.forecasting.compose import ForecastX
from sktime.forecasting.naive import NaiveForecaster

y, X = load_longley()
pipe = ForecastX(NaiveForecaster(), NaiveForecaster())
pipe = pipe.fit(y, X=X, fh=[1, 2, 3])

# predicting future with identical fh - works
pipe.predict([1, 2, 3])

# predicting future with shuffled fh - works
pipe.predict([3, 1, 2])

# predicting future with subset of fh - fails
pipe.predict([1, 2])

# attempting in-sample prediction - fails
pipe.predict([-3])
```

## Error Message

```pycon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/venv/lib/python3.11/site-packages/sktime/forecasting/base/_base.py", line 396, in predict
    fh = self._check_fh(fh)
         ^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/sktime/forecasting/base/_base.py", line 1693, in _check_fh
    raise ValueError(
ValueError: A different forecasting horizon `fh` has been provided from the one seen in `fit`. If you want to change the forecasting horizon, please re-fit the forecaster. This is because fitting of the `ForecastX` depends on `fh`.
```

**Comment by fkiraly** [comment]
I've used this PR https://github.com/sktime/sktime/pull/4699 to diagnose which forecaster is actually causing the issue. Initially, I believed it was probably the `X`-forecaster, but it is actually `ForecastX` itself.

So, this is not about `ForecastX` specifically, but about the general interface contract in relation to `fh` being present in both `fit` and `predict` (would suggest renaming the issue hence).

The two failure cases are instances of:

1. `fh` in `predict` is distinct but a strict subset of the one passed in `fit`
2. `fh` in `predict` is distinct from the one passed in `fit` but not a strict subset

Currently, whenever `fh` are distinct an error is raised.

One may now question whether that's the best thing to do, because:

* in case 1, one could simply subset to the rows after forecasting, as a default. Although the discrepancy could also be due to user error - the same behaviour could be achieved by just specifying the second `fh` once, in `fit`.
* in case 2, I don't think there's a general alternative sensible behaviour (is there?), but there might be in the sub-case where the forecaster does not require `fh` in fit. In such a case, one might have either `predict`-`fh` override `fit`-`fh`; `fit`-`fh` override `predict`-`fh`. Although since they are discrepant, there might be a good chance it is user error?

**Comment by fkiraly** [comment]
@yarnabrina, I'm curious, could you explain in more detail why this frustrates your user expectation? What do you think should happen?

**Comment by yarnabrina** [comment]
I also expected that this is from `forecaster_X`, and thought it's failing as it does not have the exogenous variables necessary to make the prediction.

Strict Subset case: I expect it to work as it's not uncommon to prepare a model for long term forecast and then use subsets of predictions (and even updating the model with new data as they become available without a complete re-fit).

Non Subset case: Since I assumed that the error is coming from `forecaster_X`, I was considering that this can be split into positive and negative horizons.

After a model is fit, it's a common expectation to get training evaluation metrics. Obviously validation data will be much more useful, but sometimes it's just not feasible with amount of data available. This is for the negative only case.

For the other case where it includes at least one positive timestep beyond the timesteps passed to `fit`, I'd agree that's highly likely to be user error.

In case where maximum of horizon passed in prediction is less than maximum timestep passed in training, I'm not sure what to consider in that case. Just from `sktime` perspective, it's user error. But most, if not all, forecasting packages use horizon as a natural number and predict for the entire range. So users may be using from that perspective, especially the new users.

(Said a lot of things, not sure if this was your question. If I misinterpreted completely, apologies.)

**Comment by fkiraly** [comment]
> (Said a lot of things, not sure if this was your question. If I misinterpreted completely, apologies.)

Nono, this is exactly the topic, and you added more cases that are useful to consider.

May I try to rephrase to see whether I understood what you were saying:

1. `fh` passed in `predict` and in `fit`, and `predict`-`fh` is strict subset of `fit`-`fh` - you think it should just subset the return.
2. it might be good idea if we allow integers as forecasting horizons. This should be interpreted as `[1, 2, ..., the_integer]`.
3. allowing `predict` with in-sample `fh` after fitting with out-of-sample `fh` might be a user expectation in an evaluation case, especially in cases where the model computes all in-sample fits already and we just need to access these.

Translating these into change items, this would be:

1. `BaseForecaster` logic change, no deprecation needed as it changes only a failure case to a function case. Needs tests and doccs.
2. `BaseForecaster` logic change, no deprecation needed as it changes only a failure case to a function case. Needs tests and docs.
3. how would I translate this? Not sure. I'd introduce a tag for forecasters that "compute in-sample forecasts anyway", e.g., `capability:insample:precomputes` or similar (sth less clunky). Then an interface change conditional in the tag, possibly a contract extension and a test. Seems most complicated of the three.

**Comment by fkiraly** [comment]
> Regarding point 2,

I see - in that case I would tend to be against changing the behaviour of `fh=5`. It's also confusing if `fh=[5]` does sth different.

On that note, I think using `range` instead of `np.range` doesn't work, but it probably should? That might be just a coercion.

> If you mean which algorithms "actually" pre-computes the in-sample fits, i.e. it's already calculated and stored in a property and all we'll do is access that, I do not know.
> But if you mean which algorithms allow in-sample prediction without asking for any more inputs, except possibly horizon specification or confidence level specifications, I'd guess quite a few (if not all?).

I see the distinction, thanks for pointing this out.

To be more precise: Upon refining my thoughts, I do not mean "calculate and store", I simply mean, the computational and memory cost of obtaining in-sample predictions is nil. The distinction is about "does there exist a computational bottleneck between the request and the response" (when requesting in-sample predictions of arbitrary horizon not previously passed).

That would be your second option plus the assumption that it comes at negligible computational cost, for which "calculate and store" is sufficient but not necessary.

**Comment by fkiraly** [comment]
Re how to take it from here, I would suggest:

* let's split up the interface changes that do not require deprecation into individual implementation tickets:
    * allowing strict sub-set of `fh` in `predict`
    * allowing `range` as an `fh`
* let's split up the interface changes that require deprecation and we think we haven't settled on in separate discussion & design issues
    * do we want integer to mean one-element-list or range? (I would say: let's not change this; not sure what your opinion is)
        * unless we already agree here on the "todo" (or "not to do") 
    * how do we handle estimators that allow easy, fast access to arbitrary in-sample predictions upon request
        * with the sub-question: how many of these are there?
        * with the sub-questions: do we handle this by tag, how do we test, etc

**Comment by yarnabrina** [comment]
> let's split up the interface changes that do not require deprecation into individual implementation tickets:

Agreed on both the points.

> do we want integer to mean one-element-list or range? (I would say: let's not change this; not sure what your opinion is)

I am okay to not change the current behaviour, but in that case I'll suggest to add a explicit note in the documentation about `int` case. Given that `sktime` differs from most forecasting libraries, I think it's worth mentioning.

(Adding a side note here, I think documentation/examples of `ForecastingHorizon` can be improved. It does not specify what does horizon of `k` mean, where `k` can be negative, zero or positive. No example contains any non-positive case, or integer/timedelta cases. I'm probably biased here, having confused `-1` should be last known data multiple times while actually its `0`, but may be it's just me.)

> how do we handle estimators that allow easy, fast access to arbitrary in-sample predictions upon request

(The following assumes that we are talking about forecasters in general here, i.e. anything that inherits from `BaseForecaster`, not just `ForecastX`. I'm not sure if something will vary for that, but just adding a disclaimer.)

I'm not very well familiar with `BaseForecaster` and `ForecastingHorizon`, but I suppose there is a way to detect maximum horizon (`fh.to_relative(self.cutoff)[-1]`?). If that is negative (when considered relative case), that ensures that user doesn't want any future prediction. Similarly if we can get the minimum one (`fh.to_relative(self.cutoff)[0]`?), and that is not older than first training data (comparison with `len(self._y)`?), I think the checking is complete to ensure this is indeed the case we want to cover. Then I propose we call a new method `_predict_in_sample` or similar to get the predictions and return the results. Suggesting a new method as I think exogenous variables will be manadotry (please correct me if I'm wrong) for `predict` if passed in `fit` but we do not need that for in-sample fits, and I'm not visualising this method to nothing except calling the estimator's in-sample prediction method, with a possible subsetting.

No comment as of now regarding the sub-questions, don't have full clarity yet.

---

Editing to add a doubt, @fkiraly are you considering the case where `predict` contains future horizons not newer than maximum horizon, but also not part of the provided horizon? What I mean is are you considering the case where `fit` had `fh=[2,3,5,7]`, and predict is `fh=[1,4,6]`? It's not a strict subset, in fact not even a subset. Shall we consider this as a user error and let it fail? I was suggesting to allow this earlier, not sure if you think it won't be possible and/or out of scope?

**Comment by fkiraly** [comment]
>> let's split up the interface changes that do not require deprecation into individual implementation tickets:

>Agreed on both the points. I can give a shot at these two over this weekend.

👍

**Comment by fkiraly** [comment]
>> do we want integer to mean one-element-list or range? (I would say: let's not change this; not sure what your opinion is)

> I think documentation/examples of `ForecastingHorizon` can be improved.

Absolutely - I suppose it should be primarily improved in the `BaseForecaster` docstrings and perhaps the forecasting tutorial? Or somewhere else too?

> I'm probably biased here, having confused `-1` should be last known data multiple times while actually its `0`, but may be it's just me.

That's actually a conscious decision to make "1" consistent with the time difference (delta) case. When there are no periods, the only reference point for "0" that makes sense (imo) is the cutoff. Therefore "1" must be strictly in the future, so in the one-period case it must be the next period, if we want consistency between no-period and period case.

**Comment by fkiraly** [comment]
> The following assumes that we are talking about forecasters in general here, i.e. anything that inherits from `BaseForecaster`, not just `ForecastX`. I'm not sure if something will vary for that, but just adding a disclaimer.

I've changed this issue to be about that, since after the first few posts that's actually what the discussion moved to imo. Kindly comment if you disagree.

**Comment by fkiraly** [comment]
>> how do we handle estimators that allow easy, fast access to arbitrary in-sample predictions upon request

>I'm not very well familiar with `BaseForecaster` and `ForecastingHorizon`, but I suppose there is a way to detect maximum horizon (`fh.to_relative(self.cutoff)[-1]`?). 

Not a dedicated method afaik, but I wonder whether we should have one.

> Then I propose we call a new method `_predict_in_sample` or similar to get the predictions and return the results. 

Such a method exists for some adapters or estimators already, but not for the base class. Perhaps we could use that as a more general interface assumption?

>Suggesting a new method as I think exogenous variables will be manadotry (please correct me if I'm wrong) for `predict` if passed in `fit` 

not correct - `ForecastX` is actually a counterexample for this.

**Comment by fkiraly** [comment]
> Editing to add a doubt, @fkiraly are you considering the case where `predict` contains future horizons not newer than maximum horizon, but also not part of the provided horizon? What I mean is are you considering the case where `fit` had `fh=[2,3,5,7]`, and predict is `fh=[1,4,6]`? It's not a strict subset, in fact not even a subset. Shall we consider this as a user error and let it fail? I was suggesting to allow this earlier, not sure if you think it won't be possible and/or out of scope?

Not all forecasters have the property that they automatically compute predictions for all periods up to the maximum, although some forecasters do have that property, especially classical ones.

Where with "automatically compute" I mean there is no significant additional compute to do from the point on where you computed the max horizon forecast.

A counterexample to that property would be the direct reduction forecaster. Here there is actually significant additional cost to compute forecasts for more `fh` elements.

**Comment by yarnabrina** [comment]
@fkiraly Is the following code snippet behave as you expect it to? Based on your above comments since start of this discussion, my expectation was that all of `predict_fh_1`, `predict_fh_2` and `predict_fh_3` should fail with error citing mismatch with `fit_fh`. But actually, all of them (except `ForecastX`) all work for me. I'm on `main` branch, at commit c98788b2.

```python3
from sktime.datasets import load_longley
from sktime.forecasting.arima import ARIMA
from sktime.forecasting.compose import ForecastX
from sktime.forecasting.var import VAR

y, X = load_longley()

fit_fh = [1, 2, 3]

arima_model = ARIMA()  # tested with AutoETS, NaiveForecaster, SARIMAX, etc. as well
arima_model.fit(y, fh=fit_fh)

var_model = VAR()
var_model.fit(X, fh=fit_fh)

composite_model = ForecastX(ARIMA(), VAR())
composite_model.fit(y, X=X, fh=fit_fh)

# all works - uses fit_fh
arima_model.predict()
var_model.predict()

predict_fh_1 = [-4, -2]  # mutually exclusive with fit_fh
predict_fh_2 = [1, 3]  # proper subset of fit_fh
predict_fh_3 = [-3, -1, 0, 2, 4]  # non-null intersection with fit_fh, not subset

# all works
arima_model.predict(fh=predict_fh_1)
var_model.predict(fh=predict_fh_1)

# all works
arima_model.predict(fh=predict_fh_2)
var_model.predict(fh=predict_fh_2)

# all works
arima_model.predict(fh=predict_fh_3)
var_model.predict(fh=predict_fh_3)

# works
composite_model.predict()

# all fails
composite_model.predict(fh=predict_fh_1)
composite_model.predict(fh=predict_fh_2)
composite_model.predict(fh=predict_fh_3)
```

> So, this is not about ForecastX specifically, but about the general interface contract in relation to a non-None fh being present in both fit and predict (would suggest renaming the issue hence).

Am I missing something in the above example, or is `ForecastX` behaving different than other estimators?

In case it is affecting somehow, does `"requires-fh-in-fit": True` have a role here? Like, estimators with this tag as `False`, which is all of the ones I tested, are not affected by difference in `fit-fh` and `predict-fh`?

**Comment by fkiraly** [comment]
> In case it is affecting somehow, does `"requires-fh-in-fit": True` have a role here?

I think that's it, you are right - if it is `False`, then the `predict` `fh` might just always override a `fit` `fh`.

Whereas `ForecastX` currently requires `fh` in `fit` even if all the components do not.

Now, theoretically, it should not require `fh` in `fit` if both components do not require it, because in that case both the `fh` for `X` and `y` can be specified in `predict` - but that would require checking some `__init__` logic.

**Comment by fkiraly** [comment]
@yarnabrina, pinging you for awareness of this - should we turn this into decisions or implementation issues?

**Comment by yarnabrina** [comment]
Sure, implementations sounds more appropriate. I am acutally facing related (I think) issues, so will probably take a look at this weekend to find any quick ideas.
