### ISSUE TITLE
[BUG] Prediction with DatetimeIndex as ForecastingHorizon values

### ISSUE THREAD

**Issue by aiwalter** [alan-turing-institute/sktime#550]
**Describe the bug**
There is an issue with `DatetimeIndex` in `ForecastingHorizon` when doing prediction. Seems this came up by recent commits?

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-0c038f527191> in <module>
      9 forecaster = NaiveForecaster(strategy="last", sp=12)
     10 forecaster.fit(y_train)
---> 11 y_pred = forecaster.predict(fh)
     12 y_pred

~\Desktop\sktime\sktime\sktime\forecasting\base\_sktime.py in predict(self, fh, X, return_pred_int, alpha)
    216         self.check_is_fitted()
    217         self._set_fh(fh)
--> 218         return self._predict(self.fh, X, return_pred_int=return_pred_int, alpha=alpha)
    219 
    220     def compute_pred_int(self, y_pred, alpha=DEFAULT_ALPHA):

~\Desktop\sktime\sktime\sktime\forecasting\base\_sktime.py in _predict(self, fh, X, return_pred_int, alpha)
    616 
    617         # all values are out-of-sample
--> 618         if fh.is_all_out_of_sample(self.cutoff):
    619             return self._predict_fixed_cutoff(
    620                 fh.to_out_of_sample(self.cutoff), **kwargs

~\Desktop\sktime\sktime\sktime\forecasting\base\_fh.py in is_all_out_of_sample(self, cutoff)
    346             cutoff.
    347         """
--> 348         return sum(self._is_out_of_sample(cutoff)) == len(self)
    349 
    350     def to_indexer(self, cutoff=None, from_cutoff=True):

~\Desktop\sktime\sktime\sktime\forecasting\base\_fh.py in _is_out_of_sample(self, cutoff)
    328         """Get index location of out-of-sample values"""
    329         # return ~self._in_sample_idx(cutoff)
--> 330         return self.to_relative(cutoff).to_pandas() > 0
    331 
    332     def is_all_out_of_sample(self, cutoff=None):

~\Desktop\sktime\sktime\sktime\forecasting\base\_fh.py in to_relative(self, cutoff)
    223                 values = _coerce_duration_to_int(values, unit=_get_unit(cutoff))
    224 
--> 225             return self._new(values, is_relative=True)
    226 
    227     @lru_cache(typed=True)

~\Desktop\sktime\sktime\sktime\forecasting\base\_fh.py in _new(self, values, is_relative)
    160         if is_relative is None:
    161             is_relative = self.is_relative
--> 162         return type(self)(values, is_relative)
    163 
    164     @property

~\Desktop\sktime\sktime\sktime\forecasting\base\_fh.py in __init__(self, values, is_relative)
    137         if not isinstance(is_relative, bool):
    138             raise TypeError("`is_relative` must be a boolean")
--> 139         values = _check_values(values)
    140 
    141         # check types, note that isinstance() does not work here because index

~\Desktop\sktime\sktime\sktime\forecasting\base\_fh.py in _check_values(values)
    105     # check values does not contain duplicates
    106     if len(values) != values.nunique():
--> 107         raise ValueError("`values` must not contain duplicates.")
    108 
    109     # return sorted values

ValueError: `values` must not contain duplicates.
```

**To Reproduce**
```python
from sktime.forecasting.all import *

y = load_airline()
y.index = y.index.to_timestamp()
y_train, y_test = temporal_train_test_split(y, test_size=44)

fh = ForecastingHorizon(y_test.index[0:5], is_relative=False)

forecaster = NaiveForecaster(strategy="last", sp=12)
forecaster.fit(y_train)
y_pred = forecaster.predict(fh)
y_pred
```

**Versions**
Current master

**Comment by mloning** [comment]
That seems related to #534, no? Actually, when I run this it, it works? But the `predict` call is extremely slow, very strange. Still have to look into this.

**Comment by aiwalter** [comment]
Sry, I was not sure if this is the same issue. Btw I tried this also on my Linux Azure VM and I got a different error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aiwalter/notebooks/sktime/sktime/sktime/forecasting/base/_sktime.py", line 218, in predict
    return self._predict(self.fh, X, return_pred_int=return_pred_int, alpha=alpha)
  File "/home/aiwalter/notebooks/sktime/sktime/sktime/forecasting/base/_sktime.py", line 620, in _predict
    fh.to_out_of_sample(self.cutoff), **kwargs
  File "/home/aiwalter/notebooks/sktime/sktime/sktime/forecasting/base/_sktime.py", line 654, in _predict_fixed_cutoff
    fh, X, return_pred_int=return_pred_int, alpha=alpha
  File "/home/aiwalter/notebooks/sktime/sktime/sktime/forecasting/naive.py", line 166, in _predict_last_window
    last_window = np.tile(last_window, reps=reps)
  File "<__array_function__ internals>", line 6, in tile
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/numpy/lib/shape_base.py", line 1258, in tile
    c = c.reshape(-1, n).repeat(nrep, 0)
MemoryError: Unable to allocate 98.5 GiB for an array with shape (1101600000, 12) and data type float64
```
Not sure what it tried to allocate here

**Comment by mloning** [comment]
Yes I think this is due to what I describe in #543 where it takes "MS" months start as "ms" for milliseconds. That explains why it becomes so slow in my case too. I'll close this one in favour of the other one.

**Comment by aiwalter** [comment]
okay thx for having a look into it!
