### ISSUE TITLE
[BUG] Can't install sktime with pip ; building wheels fail

### ISSUE THREAD

**Issue by sonoff2** [alan-turing-institute/sktime#592]
When running `pip install sktime`, following error occurs :

```cmd
Building wheels for collected packages: sktime
  Building wheel for sktime (setup.py) ... |
  ( . . . )
  copying sktime\datasets\data\ACSF1\ACSF1_TRAIN.ts -> build\bdist.win32\wheel\.\sktime\datasets\data\ACSF1\
  creating build\bdist.win32\wheel\sktime\datasets\data\Uschange
  copying sktime\datasets\data\Uschange\Uschange.csv -> build\bdist.win32\wheel\.\sktime\datasets\data\Uschange\
  running install_clib
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
  running install_egg_info
  running egg_info
  writing sktime.egg-info\PKG-INFO
  writing dependency_links to sktime.egg-info\dependency_links.txt
  writing requirements to sktime.egg-info\requires.txt
  writing top-level names to sktime.egg-info\top_level.txt
  reading manifest file 'sktime.egg-info\SOURCES.txt'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\helen\AppData\Local\Temp\pip-install-_in7hoal\sktime_21287ceb31a540d8b1dc9db7c65dd6e7\setup.py", line 319, in <module>
      setup_package()
    File "C:\Users\helen\AppData\Local\Temp\pip-install-_in7hoal\sktime_21287ceb31a540d8b1dc9db7c65dd6e7\setup.py", line 315, in setup_package
      setup(**metadata)
    File "c:\users\helen\python385\lib\site-packages\numpy\distutils\core.py", line 169, in setup
      return old_setup(**new_attr)
    File "c:\users\helen\python385\lib\site-packages\setuptools\__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "c:\users\helen\python385\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\helen\python385\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "c:\users\helen\python385\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\helen\python385\lib\site-packages\wheel\bdist_wheel.py", line 335, in run
      self.run_command('install')
    File "c:\users\helen\python385\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\helen\python385\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\helen\python385\lib\site-packages\numpy\distutils\command\install.py", line 60, in run
      r = self.setuptools_run()
    File "c:\users\helen\python385\lib\site-packages\numpy\distutils\command\install.py", line 34, in setuptools_run
      return distutils_install.run(self)
    File "c:\users\helen\python385\lib\distutils\command\install.py", line 557, in run
      self.run_command(cmd_name)
    File "c:\users\helen\python385\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\helen\python385\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\helen\python385\lib\site-packages\setuptools\command\install_egg_info.py", line 34, in run
      self.run_command('egg_info')
    File "c:\users\helen\python385\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\helen\python385\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\helen\python385\lib\site-packages\numpy\distutils\command\egg_info.py", line 25, in run
      _egg_info.run(self)
    File "c:\users\helen\python385\lib\site-packages\setuptools\command\egg_info.py", line 297, in run
      self.find_sources()
    File "c:\users\helen\python385\lib\site-packages\setuptools\command\egg_info.py", line 304, in find_sources
      mm.run()
    File "c:\users\helen\python385\lib\site-packages\setuptools\command\egg_info.py", line 535, in run
      self.add_defaults()
    File "c:\users\helen\python385\lib\site-packages\setuptools\command\egg_info.py", line 579, in add_defaults
      self.read_manifest()
    File "c:\users\helen\python385\lib\site-packages\setuptools\command\sdist.py", line 220, in read_manifest
      self.filelist.append(line)
    File "c:\users\helen\python385\lib\site-packages\setuptools\command\egg_info.py", line 477, in append
      path = convert_path(item)
    File "c:\users\helen\python385\lib\distutils\util.py", line 122, in convert_path
      raise ValueError("path '%s' cannot be absolute" % pathname)
  ValueError: path '/Users/travis/miniconda/envs/testenv/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h' cannot be absolute
  ----------------------------------------
  ERROR: Failed building wheel for sktime

```

I also tried `pip install -e .` after downloading master on github :

```cmd
Installing collected packages: sktime
  Running setup.py develop for sktime
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\helen\python385\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\helen\\code_vincent\\python_libs\\sktime-master\\setup.py'"'"'; __file__='"'"'C:\\Users\\helen\\code_vincent\\python_libs\\sktime-master\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: C:\Users\helen\code_vincent\python_libs\sktime-master\
    Complete output (29 lines):
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tctest_openmp.c /Foobjects\test_openmp.obj /openmp
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\bin\HostX86\x86\link.exe /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\lib\x86 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x86 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x86 objects\test_openmp.obj /OUT:test_openmp.exe /openmp
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\helen\code_vincent\python_libs\sktime-master\setup.py", line 325, in <module>
        setup_package()
      File "C:\Users\helen\code_vincent\python_libs\sktime-master\setup.py", line 321, in setup_package
        setup(**metadata)
      File "c:\users\helen\python385\lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "C:\Users\helen\code_vincent\python_libs\sktime-master\setup.py", line 216, in configuration
        config.add_subpackage("sktime")
      File "c:\users\helen\python385\lib\site-packages\numpy\distutils\misc_util.py", line 1018, in add_subpackage
        config_list = self.get_subpackage(subpackage_name, subpackage_path,
      File "c:\users\helen\python385\lib\site-packages\numpy\distutils\misc_util.py", line 984, in get_subpackage
        config = self._get_configuration_from_setup_py(
      File "c:\users\helen\python385\lib\site-packages\numpy\distutils\misc_util.py", line 926, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "sktime\setup.py", line 28, in configuration
        maybe_cythonize_extensions(top_path, config)
      File "C:\Users\helen\code_vincent\python_libs\sktime-master\sktime\_build_utils\__init__.py", line 53, in maybe_cythonize_extensions
        import Cython
    ModuleNotFoundError: No module named 'Cython'
    Error in atexit._run_exitfuncs:
    Traceback (most recent call last):
      File "c:\users\helen\python385\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
        return stream.closed
    ValueError: underlying buffer has been detached
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\helen\python385\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\helen\\code_vincent\\python_libs\\sktime-master\\setup.py'"'"'; __file__='"'"'C:\\Users\\helen\\code_vincent\\python_libs\\sktime-master\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

```

I am currently running :

```cmd
Python version
3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:43:08) [MSC v.1926 32 bit (Intel)]
Version info.
sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)

```

Not really sure what to do next ?

**Comment by mloning** [comment]
Hi @sonoff2, looks like we're not providing a wheel for your platform (OS) which I'm assuming requires the `win_amd64.whl` wheel. 

Could you try to follow the [installation instructions](https://www.sktime.org/en/latest/installation.html) to see if you can compile it locally? The error above simply due to missing Cython.

**Comment by sonoff2** [comment]
Hello, thank you for your help.
First time doing this : just to make sure, we are talking about following doc instructions in :
_Installation > Development version >Installing build dependencies > Windows ?_

Or are we talking about following doc instructions in :
_Installation > Development version > Building binary packages and installers_
which is basically running 

```cmd
pip install wheel
python setup.py bdist_wheel bdist_wininst

```
?

**Comment by mloning** [comment]
@sonoff2 alright, great, that's good to know!

That also means that it should be quite easy to set up an addition CI/CD workflow for the `win_amd64.whl`. We should consider moving away from appveyor though as it is a lot slower than GitHub Actions or Azure.

**Comment by vaknin** [comment]
Just a heads up, I'm unable to install sktime as well, I'll try what @sonoff2 suggested.

**Comment by mloning** [comment]
@vaknin no, you only have to build it once, after that it's installed in your environment. Whether you have to build the dependencies depends on whether they provide the wheel that you need.

**Comment by vaknin** [comment]
> @vaknin no, you only have to build it once, after that it's installed in your environment. Whether you have to build the dependencies depends on whether they provide the wheel that you need.

Cheers.
If it helps anyone, I found that using sktime via conda is easier and returns no errors (for amd64).

**Comment by mertbozkir** [comment]
@vaknin can you write how you install in conda? 

![image](https://user-images.githubusercontent.com/63906053/116388413-7c24af00-a824-11eb-98ed-91a8a2febd1f.png)

I am still trying to solve this installation problem.

**Comment by mertbozkir** [comment]
Before this code I tried 
```
pip install sktime[all_extras]
``` 

![image](https://user-images.githubusercontent.com/63906053/116391200-8a27ff00-a827-11eb-8454-2633fe83ae69.png)
**I finally installed sktime, but now it's for pmdarima module. :(** 


![image](https://user-images.githubusercontent.com/63906053/116391289-a0ce5600-a827-11eb-9168-1d75bd90e974.png)

**Comment by mloning** [comment]
@mertbozkir does `pip install pmdarima` not work?

**Comment by ParthivNaresh** [comment]
@mloning @mertbozkir @vaknin I'm trying to install `sktime` and `pmdarima` via conda exclusively within a feedstock, has anyone been able to install both `sktime` and `pmdarima` via conda without running into package conflict issues?

**Comment by mloning** [comment]
@ParthivNaresh wasn't aware of this, but I can reproduce the package conflict. Would you like to look into it and see which requirements we have to adjust to avoid the conflict?

**Comment by mloning** [comment]
See #860

**Comment by CathyF9600** [comment]
As a note, for me to run `python setup.py bdist_wheel` in the doc instructions, I had to download "[Microsoft C++ Build Tools"](https://docs.microsoft.com/en-us/answers/questions/136595/error-microsoft-visual-c-140-or-greater-is-require.html)

**Comment by Proelf** [comment]
I cant open [installation instructions](https://www.sktime.org/en/latest/installation.html)；

**Comment by fkiraly** [comment]
@Proelf, this is an old issue - the domain sktime.org has been swooped up by a third party and is no longer where the docs are. The instructions are now on sktime.net - I updated all the links above to avoid confusion.
