### ISSUE TITLE
ThetaForecaster does not work with time series containig negative values

### ISSUE THREAD

**Issue by ngupta23** [alan-turing-institute/sktime#940]
**Is your feature request related to a problem? Please describe.**
`ThetaForecaster` does not work with negative values

**Describe the solution you'd like**
I am trying to train the theta model on a time series with negative values. But it looks like the default deseasonalizing is set to multiplicative which causes this to fail. Is it possible to provide the component types so that it can be externally set to additive when there are negative values? Or does the `ThetaForecaster` have to be defined with multiplicative deseasonalizer only?

```python
from sktime.datasets import load_airline
from sktime.forecasting.theta import ThetaForecaster

y = load_airline() - 400  # simulate negative values
forecaster = ThetaForecaster(sp=12)
forecaster.fit(y)
```

```python
Traceback (most recent call last):
  File "c:/Users/Nikhil/OneDrive/my_libraries/my_python_libraries/pycaret_dev/time_series_debug_white_noise.py", line 49, in <module>
    forecaster.fit(y)
  File "C:\Users\Nikhil\AppData\Roaming\Python\Python37\site-packages\sktime\forecasting\theta.py", line 127, in fit
    y = self.deseasonalizer_.fit_transform(y)
  File "C:\Users\Nikhil\AppData\Roaming\Python\Python37\site-packages\sktime\transformations\base.py", line 88, in fit_transform
    return self.fit(Z).transform(Z)
  File "C:\Users\Nikhil\AppData\Roaming\Python\Python37\site-packages\sktime\transformations\series\detrend\_deseasonalize.py", line 89, in fit
    extrapolate_trend=0,
  File "C:\ProgramData\Anaconda3\envs\pycaret_dev\lib\site-packages\pandas\util\_decorators.py", line 199, in wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\pycaret_dev\lib\site-packages\statsmodels\tsa\seasonal.py", line 135, in seasonal_decompose
    raise ValueError("Multiplicative seasonality is not appropriate "
ValueError: Multiplicative seasonality is not appropriate for zero and negative values
```

**Describe alternatives you've considered**

Run without deseasonalizing works but would be nice to work with deseasonalize=True as well.
```python
forecaster = ThetaForecaster(sp=12, deseasonalize=False)
forecaster.fit(y)
```

**Comment by mloning** [comment]
We have to look into this. There's currently an effort to refactor Theta to make it more modular (see #923). As a work around for now you could use pipelining, i.e. `TransformedTargetForecaster(Deseasonalizer(...), Theta(...))`.

**Comment by jbbqqf** [comment]
Hi! Triaging older issues this week — I think this one has shipped and can be closed.

`ThetaForecaster` now exposes `deseasonalize_model` (default `"multiplicative"`, settable to `"additive"`), so series with negative values can be handled by switching the decomposition mode (or by disabling deseasonalisation entirely with `deseasonalize=False`):

- [`sktime/forecasting/theta.py:59`](https://github.com/sktime/sktime/blob/main/sktime/forecasting/theta.py#L59) — docstring for `deseasonalize_model`.
- [`sktime/forecasting/theta.py:127`](https://github.com/sktime/sktime/blob/main/sktime/forecasting/theta.py#L127) — `__init__` signature exposes it.

```python
from sktime.forecasting.theta import ThetaForecaster
f = ThetaForecaster(deseasonalize_model="additive", sp=12)  # works with negatives
```

Would you mind closing this out? If `additive` still misbehaves on a concrete example you have, please share it and I'll dig further.

(Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the references above were verified manually against the current `main` branch at commit `bd8fe08`.)
